# Ludork Avalonia-Lua Version Configuration
# Sourced by init scripts — change versions here, not in individual scripts.

LUASF_VERSION=v3.1.0.8
LUASF_VARIANT=ME
SFML_REPOSITORY=JasonLeon01/SFML-ME
SFML_TAG=310-ME-OH-GLESVER
SOL2_VERSION=3.3.0
LUA_VERSION=5.5.0
LUA_SHA256=57ccc32bbbd005cab75bcc52444052535af691789dba2b9016d5c50640d68b3d
LUA_CJSON_VERSION=2.1.0.19
ZLIB_VERSION=1.3.1
FFMPEG_VERSION=8.1.2
FFMPEG_COMMIT=38b88335f99e76ed89ff3c93f877fdefce736c13
GNU_MAKE_VERSION=4.4.1
WIX_VERSION=6.0.2
