---@meta Enums.GeneralData.Item
--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.GeneralData.Item
local Item = {
    BreakIce = "BreakIce",
    BreakLava = "BreakLava",
    BreakWall = "BreakWall",
    CentreFly = "CentreFly",
    ClearWall = "ClearWall",
    DownFly = "DownFly",
    EnemyBook = "EnemyBook",
    KEY_B = "KEY_B",
    KEY_R = "KEY_R",
    KEY_Y = "KEY_Y",
    PoisonedEase = "PoisonedEase",
    PoisonedRelease = "PoisonedRelease",
    Teleport = "Teleport",
    UpFly = "UpFly",
    WeakEase = "WeakEase",
    WeakRelease = "WeakRelease",
}

return Item
