---@meta Enums.GeneralData.Special
--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.

---@enum Enums.GeneralData.Special
local Special = {
    Blockade = "Blockade",
    Compete = "Compete",
    Domain = "Domain",
    First = "First",
    FixDmg = "FixDmg",
    Flank = "Flank",
    Hard = "Hard",
    Magic = "Magic",
    MultiHit = "MultiHit",
    Poisoning = "Poisoning",
    Reborn = "Reborn",
    Vampire = "Vampire",
    Weaken = "Weaken",
}

return Special
