using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

namespace Ludork.Plugins.OfficialLocaleTools;

internal sealed record DuplicateLocaleId(
    string Id,
    string FirstLocation,
    string DuplicateLocation);

internal sealed record LocaleExportResult(
    int LanguageCount,
    int EntryCount,
    IReadOnlyList<DuplicateLocaleId> Duplicates);

internal static class LocaleExporter
{
    public const string GeneratedMarker = "-- AUTO-GENERATED by Ludork Official Locale Tools. DO NOT EDIT.";
    private const int RetryMilliseconds = 10_000;
    private const int InitialDelayMilliseconds = 50;
    private const int MaximumDelayMilliseconds = 400;

    private sealed record PendingLocaleFile(string TemporaryPath, string DestinationPath);

    public static LocaleExportResult Export(
        string workbookPath,
        string outputDirectory,
        CancellationToken cancellationToken)
    {
        LocaleWorkbookData workbook = XlsxLocaleWorkbookReader.Read(workbookPath, cancellationToken);
        Directory.CreateDirectory(outputDirectory);

        List<PendingLocaleFile> pendingFiles = new List<PendingLocaleFile>();
        try
        {
            foreach (KeyValuePair<string, IReadOnlyDictionary<string, string>> languageEntry in
                     workbook.Languages.OrderBy(entry => entry.Key, StringComparer.Ordinal))
            {
                cancellationToken.ThrowIfCancellationRequested();
                string destinationPath = Path.Combine(outputDirectory, GetFileName(languageEntry.Key));
                string temporaryPath = Path.Combine(
                    outputDirectory,
                    "." + languageEntry.Key + "." + Guid.NewGuid().ToString("N") + ".tmp");
                PendingLocaleFile pendingFile = new PendingLocaleFile(temporaryPath, destinationPath);
                pendingFiles.Add(pendingFile);
                WriteUtf8File(temporaryPath, BuildLuaTable(languageEntry.Value));
            }

            foreach (PendingLocaleFile pendingFile in pendingFiles)
            {
                cancellationToken.ThrowIfCancellationRequested();
                InstallFile(pendingFile);
            }
            HashSet<string> outputPaths = pendingFiles
                .Select(file => file.DestinationPath)
                .ToHashSet(OperatingSystem.IsWindows() ? StringComparer.OrdinalIgnoreCase : StringComparer.Ordinal);
            DeleteObsoleteFiles(outputDirectory, outputPaths, cancellationToken);
        }
        finally
        {
            DeleteTemporaryFiles(pendingFiles);
        }

        int entryCount = workbook.Languages.Sum(language => language.Value.Count);
        return new LocaleExportResult(
            workbook.Languages.Count,
            entryCount,
            workbook.Duplicates);
    }

    public static string GetFileName(string language)
    {
        char[] invalidCharacters = Path.GetInvalidFileNameChars();
        if (string.IsNullOrWhiteSpace(language) ||
            language is "." or ".." ||
            string.Equals(language, "Core", StringComparison.OrdinalIgnoreCase) ||
            language.IndexOf('/') >= 0 ||
            language.IndexOf('\\') >= 0 ||
            language.IndexOfAny(invalidCharacters) >= 0 ||
            language.IndexOfAny(new[] { '<', '>', ':', '"', '|', '?', '*' }) >= 0)
        {
            throw new InvalidDataException("Invalid locale language name: " + language);
        }
        return language + ".lua";
    }

    private static void InstallFile(PendingLocaleFile pendingFile)
    {
        string destinationPath = pendingFile.DestinationPath;
        string directory = Path.GetDirectoryName(destinationPath)!;
        string fileName = Path.GetFileName(destinationPath);
        string? originalPath = null;
        if (File.Exists(destinationPath))
        {
            string[] existingPaths = Directory.GetFiles(directory);
            if (!existingPaths.Any(path => string.Equals(Path.GetFileName(path), fileName, StringComparison.Ordinal)))
            {
                originalPath = existingPaths.FirstOrDefault(path =>
                    string.Equals(Path.GetFileName(path), fileName, StringComparison.OrdinalIgnoreCase));
            }
        }
        if (originalPath is null)
        {
            MoveFile(pendingFile.TemporaryPath, destinationPath, true);
            return;
        }

        string backupPath = Path.Combine(directory, "." + fileName + "." + Guid.NewGuid().ToString("N") + ".backup");
        MoveFile(originalPath, backupPath, false);
        try
        {
            MoveFile(pendingFile.TemporaryPath, destinationPath, false);
        }
        catch
        {
            MoveFile(backupPath, originalPath, false);
            throw;
        }
        DeleteFile(backupPath);
    }

    private static void DeleteObsoleteFiles(
        string outputDirectory,
        IReadOnlySet<string> outputPaths,
        CancellationToken cancellationToken)
    {
        foreach (string path in Directory.EnumerateFiles(outputDirectory, "*.lua"))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (outputPaths.Contains(path)
                || string.Equals(Path.GetFileName(path), "Core.lua", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }
            string? marker;
            using (StreamReader reader = new StreamReader(path, new UTF8Encoding(false, true), true))
                marker = reader.ReadLine();
            if (string.Equals(marker, GeneratedMarker, StringComparison.Ordinal))
                DeleteFile(path);
        }
    }

    private static string BuildLuaTable(IReadOnlyDictionary<string, string> mapping)
    {
        StringBuilder builder = new StringBuilder();
        builder.Append(GeneratedMarker).Append("\n\nreturn {\n");
        foreach (KeyValuePair<string, string> entry in
                 mapping.OrderBy(entry => entry.Key, StringComparer.Ordinal))
        {
            builder.Append("    [");
            AppendLuaString(builder, entry.Key);
            builder.Append("] = ");
            AppendLuaString(builder, entry.Value);
            builder.Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private static void AppendLuaString(StringBuilder builder, string value)
    {
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (character < 32 || character == 127)
                    {
                        builder.Append('\\');
                        builder.Append(((int)character).ToString("D3"));
                    }
                    else
                    {
                        builder.Append(character);
                    }
                    break;
            }
        }
        builder.Append('"');
    }

    private static void WriteUtf8File(string path, string content)
    {
        UTF8Encoding encoding = new UTF8Encoding(false);
        byte[] bytes = encoding.GetBytes(content);
        using FileStream stream = new FileStream(
            path,
            FileMode.CreateNew,
            FileAccess.Write,
            FileShare.None);
        stream.Write(bytes, 0, bytes.Length);
        stream.Flush(true);
    }

    private static void MoveFile(string source, string destination, bool overwrite)
    {
        try
        {
            Retry(() =>
            {
                if (overwrite)
                    ClearReadOnly(destination);
                File.Move(source, destination, overwrite);
            });
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            throw new IOException(destination + ": " + exception.Message, exception);
        }
    }

    private static void DeleteFile(string path)
    {
        Retry(() =>
        {
            ClearReadOnly(path);
            File.Delete(path);
        });
    }

    private static void Retry(Action action)
    {
        if (!OperatingSystem.IsWindows())
        {
            action();
            return;
        }

        long deadline = Environment.TickCount64 + RetryMilliseconds;
        int delay = InitialDelayMilliseconds;
        while (true)
        {
            try
            {
                action();
                return;
            }
            catch (Exception exception) when (
                IsTransient(exception) && Environment.TickCount64 < deadline)
            {
                Thread.Sleep(delay);
                delay = Math.Min(delay * 2, MaximumDelayMilliseconds);
            }
        }
    }

    private static void ClearReadOnly(string path)
    {
        if (!File.Exists(path))
            return;
        FileAttributes attributes = File.GetAttributes(path);
        if ((attributes & FileAttributes.ReadOnly) != 0)
            File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
    }

    private static bool IsTransient(Exception exception)
    {
        int code = exception.HResult & 0xFFFF;
        return exception is UnauthorizedAccessException or IOException
            && code is 5 or 32 or 33;
    }

    private static void DeleteTemporaryFiles(IEnumerable<PendingLocaleFile> pendingFiles)
    {
        foreach (PendingLocaleFile pendingFile in pendingFiles)
        {
            try
            {
                if (File.Exists(pendingFile.TemporaryPath))
                {
                    File.Delete(pendingFile.TemporaryPath);
                }
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
        }
    }
}
