using Ludork.Models;
using MoonSharp.Interpreter;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Ludork.Services;

public sealed class GameVariableService : IGameVariableCatalog
{
    public const string GeneratedMarker = "-- AUTO-GENERATED by Ludork Game Variable Manager. DO NOT EDIT.";

    private const string RuntimeRelativePath = "Scripts/Source/Configs/GameVariables.lua";
    private const string MetadataRelativePath = "Scripts/Source/Configs/GameVariables_meta.lua";
    private static readonly UTF8Encoding utf8 = new(false, true);
    private readonly LuaMetadataService metadataService;
    private readonly List<GameVariableDefinition> variables = [];
    private bool isModified;

    public GameVariableService(string projectPath, LuaMetadataService metadataService)
    {
        if (!Path.IsPathFullyQualified(projectPath))
            throw new ArgumentException(nameof(projectPath));
        ArgumentNullException.ThrowIfNull(metadataService);
        string normalizedProjectPath = Path.TrimEndingDirectorySeparator(Path.GetFullPath(projectPath));
        if (!string.Equals(
            normalizedProjectPath,
            Path.TrimEndingDirectorySeparator(Path.GetFullPath(metadataService.ProjectPath)),
            StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(nameof(metadataService));
        }

        this.metadataService = metadataService;
        RuntimePath = Path.Combine(normalizedProjectPath, RuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        MetadataPath = Path.Combine(normalizedProjectPath, MetadataRelativePath.Replace('/', Path.DirectorySeparatorChar));

        bool runtimeExists = File.Exists(RuntimePath);
        bool metadataExists = File.Exists(MetadataPath);
        if (runtimeExists != metadataExists)
            throw new InvalidDataException("The generated game variable file pair is incomplete");
        if (runtimeExists)
            variables.AddRange(loadExisting().OrderBy(value => value.Name, StringComparer.Ordinal));
    }

    public string RuntimePath { get; }
    public string MetadataPath { get; }
    public IReadOnlyList<GameVariableDefinition> Variables => variables
        .OrderBy(value => value.Name, StringComparer.Ordinal)
        .ToArray();
    public bool IsModified => isModified;
    public event EventHandler? Changed;
    public event EventHandler? Saved;

    public static bool IsValidName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)
            || !string.Equals(name, name.Trim(), StringComparison.Ordinal)
            || string.Equals(name, "attrs", StringComparison.Ordinal))
        {
            return false;
        }
        return !name.Any(char.IsControl);
    }

    public bool TryGet(string name, out GameVariableDefinition? definition)
    {
        GameVariableDefinition? found = variables.FirstOrDefault(
            value => string.Equals(value.Name, name, StringComparison.Ordinal));
        definition = found;
        return definition is not null;
    }

    public GameVariableSaveResult EnsureGeneratedFiles()
    {
        try
        {
            bool runtimeExists = File.Exists(RuntimePath);
            bool metadataExists = File.Exists(MetadataPath);
            if (runtimeExists != metadataExists)
                throw new InvalidDataException("The generated game variable file pair is incomplete");
            if (runtimeExists)
                ensureOwned(RuntimePath);
            if (metadataExists)
                ensureOwned(MetadataPath);
            if (!runtimeExists)
                isModified = true;
        }
        catch (Exception exception) when (isSaveException(exception))
        {
            return GameVariableSaveResult.Failed(formatFailure(exception));
        }
        GameVariableSaveResult result = SavePending();
        if (!result.Success && isModified)
            Changed?.Invoke(this, EventArgs.Empty);
        return result;
    }

    public GameVariableSaveResult Create(string name, GameVariableType type)
    {
        if (!IsValidName(name))
            return GameVariableSaveResult.Failed("Game variable name is invalid");
        if (!Enum.IsDefined(type))
            return GameVariableSaveResult.Failed("Game variable type is invalid");
        if (variables.Any(value => string.Equals(value.Name, name, StringComparison.Ordinal)))
            return GameVariableSaveResult.Failed($"Game variable {name} already exists");
        variables.Add(new GameVariableDefinition(name, type, createDefault(type)));
        variables.Sort((left, right) => StringComparer.Ordinal.Compare(left.Name, right.Name));
        return saveMutation();
    }

    public GameVariableSaveResult Delete(string name)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        variables.RemoveAt(index);
        return saveMutation();
    }

    public GameVariableSaveResult ChangeType(string name, GameVariableType type)
    {
        if (!Enum.IsDefined(type))
            return GameVariableSaveResult.Failed("Game variable type is invalid");
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        GameVariableDefinition current = variables[index];
        if (current.Type == type)
            return GameVariableSaveResult.Completed(string.Empty);
        variables[index] = new GameVariableDefinition(
            current.Name,
            type,
            createDefault(type),
            current.Remark);
        return saveMutation();
    }

    public GameVariableSaveResult SetInitialValue(string name, JsonNode? initialValue)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        GameVariableDefinition current = variables[index];
        try
        {
            validateInitialValue(current.Type, initialValue);
        }
        catch (InvalidDataException exception)
        {
            return GameVariableSaveResult.Failed(exception.Message);
        }
        if (JsonNode.DeepEquals(current.InitialValue, initialValue))
            return GameVariableSaveResult.Completed(string.Empty);
        variables[index] = new GameVariableDefinition(
            current.Name,
            current.Type,
            initialValue,
            current.Remark);
        return saveMutation();
    }

    public GameVariableSaveResult SetRemark(string name, string? remark)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        string normalized = remark ?? string.Empty;
        GameVariableDefinition current = variables[index];
        if (string.Equals(current.Remark, normalized, StringComparison.Ordinal))
            return GameVariableSaveResult.Completed(string.Empty);
        variables[index] = new GameVariableDefinition(
            current.Name,
            current.Type,
            current.InitialValue,
            normalized);
        return saveMutation();
    }

    public GameVariableSaveResult SavePending()
    {
        try
        {
            bool runtimeExists = File.Exists(RuntimePath);
            bool metadataExists = File.Exists(MetadataPath);
            if (runtimeExists != metadataExists)
                throw new InvalidDataException("The generated game variable file pair is incomplete");
            if (!isModified)
                return GameVariableSaveResult.Completed(string.Empty);
            string runtimeText = renderRuntime();
            string metadataText = renderMetadata();
            IReadOnlyList<GameVariableDefinition> parsed = parseDocuments(
                runtimeText,
                metadataText,
                RuntimePath,
                MetadataPath);
            ensureEquivalent(parsed);
            writePair(runtimeText, metadataText);
        }
        catch (Exception exception) when (isSaveException(exception))
        {
            return GameVariableSaveResult.Failed(formatFailure(exception));
        }

        isModified = false;
        metadataService.ClearCache();
        Saved?.Invoke(this, EventArgs.Empty);
        Changed?.Invoke(this, EventArgs.Empty);
        return GameVariableSaveResult.Completed(
            RuntimeRelativePath + Environment.NewLine + MetadataRelativePath);
    }

    private GameVariableSaveResult saveMutation()
    {
        isModified = true;
        GameVariableSaveResult result = SavePending();
        if (!result.Success)
            Changed?.Invoke(this, EventArgs.Empty);
        return result;
    }

    private int findIndex(string name)
    {
        return variables.FindIndex(value => string.Equals(value.Name, name, StringComparison.Ordinal));
    }

    private IReadOnlyList<GameVariableDefinition> loadExisting()
    {
        ensureOwned(RuntimePath);
        ensureOwned(MetadataPath);
        string runtimeText = File.ReadAllText(RuntimePath, utf8);
        string metadataText = File.ReadAllText(MetadataPath, utf8);
        return parseDocuments(runtimeText, metadataText, RuntimePath, MetadataPath);
    }

    private static IReadOnlyList<GameVariableDefinition> parseDocuments(
        string runtimeText,
        string metadataText,
        string runtimePath,
        string metadataPath)
    {
        ensureMarker(runtimeText, runtimePath);
        ensureMarker(metadataText, metadataPath);
        DynValue runtimeRoot = execute(runtimeText, runtimePath);
        DynValue metadataRoot = execute(metadataText, metadataPath);
        validatePureRoot(runtimeRoot, runtimePath);
        validatePureRoot(metadataRoot, metadataPath);
        IReadOnlyList<MetadataEntry> metadata = parseMetadata(metadataRoot.Table, metadataPath);
        Dictionary<string, DynValue> runtimeValues = parseRuntime(runtimeRoot.Table, metadata, runtimePath);
        List<GameVariableDefinition> result = [];
        foreach (MetadataEntry entry in metadata)
        {
            JsonNode? initialValue = runtimeValues.TryGetValue(entry.Name, out DynValue? value)
                ? convertInitialValue(value, entry.Type, entry.Name)
                : null;
            result.Add(new GameVariableDefinition(entry.Name, entry.Type, initialValue, entry.Remark));
        }
        return result;
    }

    private static DynValue execute(string text, string path)
    {
        Script script = new(CoreModules.None);
        return script.DoString(text, null, path);
    }

    private static void validatePureRoot(DynValue root, string path)
    {
        if (root.Type != DataType.Table)
            throw new InvalidDataException($"{path} must return a table");
        HashSet<Table> visiting = new(ReferenceEqualityComparer.Instance);
        validatePureData(root, visiting, path);
    }

    private static void validatePureData(DynValue value, HashSet<Table> visiting, string path)
    {
        if (value.Type == DataType.Number)
        {
            if (!double.IsFinite(value.Number))
                throw new InvalidDataException($"{path} contains a non-finite number");
            return;
        }
        if (value.Type is DataType.Boolean or DataType.String or DataType.Nil or DataType.Void)
            return;
        if (value.Type != DataType.Table || value.Table is null || !visiting.Add(value.Table))
            throw new InvalidDataException($"{path} must contain only acyclic Lua data");
        foreach (TablePair pair in value.Table.Pairs)
        {
            if (pair.Key.Type is not DataType.String and not DataType.Number)
                throw new InvalidDataException($"{path} contains an unsupported table key");
            if (pair.Key.Type == DataType.Number && !double.IsFinite(pair.Key.Number))
                throw new InvalidDataException($"{path} contains a non-finite table key");
            validatePureData(pair.Value, visiting, path);
        }
        visiting.Remove(value.Table);
    }

    private static IReadOnlyList<MetadataEntry> parseMetadata(Table root, string path)
    {
        List<TablePair> rootPairs = root.Pairs.ToList();
        if (rootPairs.Count != 1
            || rootPairs[0].Key.Type != DataType.String
            || !string.Equals(rootPairs[0].Key.String, "GameVariables", StringComparison.Ordinal)
            || rootPairs[0].Value.Type != DataType.Table)
        {
            throw new InvalidDataException($"{path} must contain only GameVariables metadata");
        }

        Table typeTable = rootPairs[0].Value.Table;
        IReadOnlyList<string> attrs = readAttrs(typeTable.Get("attrs"), path);
        List<TablePair> typePairs = typeTable.Pairs.ToList();
        if (typePairs.Any(pair => pair.Key.Type != DataType.String)
            || typePairs.Count != attrs.Count + 1
            || typePairs.Any(pair => pair.Key.String != "attrs" && !attrs.Contains(pair.Key.String, StringComparer.Ordinal)))
        {
            throw new InvalidDataException($"{path} contains fields outside attrs");
        }

        List<MetadataEntry> result = [];
        foreach (string name in attrs)
        {
            DynValue fieldValue = typeTable.Get(name);
            if (fieldValue.Type != DataType.Table)
                throw new InvalidDataException($"Game variable {name} metadata must be a table");
            Table field = fieldValue.Table;
            List<TablePair> fieldPairs = field.Pairs.ToList();
            if (fieldPairs.Any(pair => pair.Key.Type != DataType.String
                || pair.Key.String is not "type" and not "Meta")
                || fieldPairs.Count(pair => pair.Key.String == "type") != 1
                || fieldPairs.Count > 2)
            {
                throw new InvalidDataException($"Game variable {name} metadata has unsupported fields");
            }
            DynValue typeValue = field.Get("type");
            if (typeValue.Type != DataType.String || !tryParseType(typeValue.String, out GameVariableType type))
                throw new InvalidDataException($"Game variable {name} has an unsupported type");
            string remark = readRemark(field.Get("Meta"), name);
            result.Add(new MetadataEntry(name, type, remark));
        }
        return result;
    }

    private static IReadOnlyList<string> readAttrs(DynValue value, string path)
    {
        if (value.Type != DataType.Table)
            throw new InvalidDataException($"{path} must declare an attrs array");
        List<TablePair> pairs = value.Table.Pairs
            .OrderBy(pair => pair.Key.Type == DataType.Number ? pair.Key.Number : double.MaxValue)
            .ToList();
        List<string> result = [];
        for (int index = 0; index < pairs.Count; index += 1)
        {
            TablePair pair = pairs[index];
            if (pair.Key.Type != DataType.Number
                || pair.Key.Number != index + 1
                || pair.Value.Type != DataType.String
                || !IsValidName(pair.Value.String))
            {
                throw new InvalidDataException($"{path} attrs must be an ordered array of valid names");
            }
            result.Add(pair.Value.String);
        }
        if (result.Distinct(StringComparer.Ordinal).Count() != result.Count)
            throw new InvalidDataException($"{path} attrs must contain unique names");
        return result;
    }

    private static string readRemark(DynValue value, string name)
    {
        if (value.Type is DataType.Nil or DataType.Void)
            return string.Empty;
        if (value.Type != DataType.Table)
            throw new InvalidDataException($"Game variable {name} Meta must be a table");
        List<TablePair> pairs = value.Table.Pairs.ToList();
        DynValue remark = value.Table.Get("Remark");
        if (pairs.Count != 1
            || pairs[0].Key.Type != DataType.String
            || pairs[0].Key.String != "Remark"
            || remark.Type != DataType.String
            || remark.String.Length == 0)
        {
            throw new InvalidDataException($"Game variable {name} Meta may only contain a non-empty Remark");
        }
        return remark.String;
    }

    private static Dictionary<string, DynValue> parseRuntime(
        Table root,
        IReadOnlyList<MetadataEntry> metadata,
        string path)
    {
        HashSet<string> names = new(metadata.Select(entry => entry.Name), StringComparer.Ordinal);
        Dictionary<string, DynValue> result = new(StringComparer.Ordinal);
        foreach (TablePair pair in root.Pairs)
        {
            if (pair.Key.Type != DataType.String || !names.Contains(pair.Key.String))
                throw new InvalidDataException($"{path} contains a variable absent from metadata");
            result.Add(pair.Key.String, pair.Value);
        }
        if (result.Count != metadata.Count)
            throw new InvalidDataException($"{path} must contain an initial value for every variable");
        return result;
    }

    private static JsonNode convertInitialValue(DynValue value, GameVariableType type, string name)
    {
        switch (type)
        {
            case GameVariableType.Bool:
                if (value.Type == DataType.Boolean)
                    return JsonValue.Create(value.Boolean);
                break;
            case GameVariableType.Int:
                if (value.Type == DataType.Number
                    && value.Number == Math.Truncate(value.Number)
                    && value.Number is >= int.MinValue and <= int.MaxValue)
                {
                    return JsonValue.Create(checked((int)value.Number));
                }
                break;
            case GameVariableType.Float:
                if (value.Type == DataType.Number && double.IsFinite(value.Number))
                    return JsonValue.Create(value.Number);
                break;
            case GameVariableType.String:
                if (value.Type == DataType.String)
                    return JsonValue.Create(value.String);
                break;
            case GameVariableType.List:
                if (value.Type == DataType.Table)
                    return tableToArray(value.Table, name);
                break;
            case GameVariableType.Dict:
                if (value.Type == DataType.Table)
                    return tableToObject(value.Table, name);
                break;
        }
        throw new InvalidDataException($"Initial value for {name} does not match {type}");
    }

    private static JsonArray tableToArray(Table table, string name)
    {
        List<TablePair> pairs = table.Pairs.OrderBy(pair => pair.Key.Number).ToList();
        JsonArray result = [];
        for (int index = 0; index < pairs.Count; index += 1)
        {
            TablePair pair = pairs[index];
            if (pair.Key.Type != DataType.Number || pair.Key.Number != index + 1)
                throw new InvalidDataException($"Initial list value for {name} must have contiguous numeric keys");
            result.Add(toJsonNode(pair.Value, name));
        }
        return result;
    }

    private static JsonObject tableToObject(Table table, string name)
    {
        JsonObject result = [];
        foreach (TablePair pair in table.Pairs)
        {
            if (pair.Key.Type != DataType.String)
                throw new InvalidDataException($"Initial dict value for {name} must have string keys");
            result.Add(pair.Key.String, toJsonNode(pair.Value, name));
        }
        return result;
    }

    private static JsonNode toJsonNode(DynValue value, string name)
    {
        return value.Type switch
        {
            DataType.Boolean => JsonValue.Create(value.Boolean),
            DataType.Number when double.IsFinite(value.Number) => numberToJson(value.Number),
            DataType.String => JsonValue.Create(value.String),
            DataType.Table => tableToUnknown(value.Table, name),
            _ => throw new InvalidDataException($"Initial value for {name} contains unsupported data"),
        };
    }

    private static JsonNode tableToUnknown(Table table, string name)
    {
        List<TablePair> pairs = table.Pairs.ToList();
        if (pairs.Count == 0)
            return new JsonObject();
        if (pairs.All(pair => pair.Key.Type == DataType.String))
            return tableToObject(table, name);
        if (pairs.All(pair => pair.Key.Type == DataType.Number))
            return tableToArray(table, name);
        throw new InvalidDataException($"Initial value for {name} contains a mixed-key table");
    }

    private static JsonNode numberToJson(double value)
    {
        if (value == Math.Truncate(value)
            && value is >= int.MinValue and <= int.MaxValue)
        {
            return JsonValue.Create(checked((int)value));
        }
        return JsonValue.Create(value);
    }

    private static void validateInitialValue(GameVariableType type, JsonNode? value)
    {
        if (value is null)
            throw new InvalidDataException($"Initial value does not match {type}");
        JsonValueKind kind = value.GetValueKind();
        bool valid = type switch
        {
            GameVariableType.Bool => kind is JsonValueKind.True or JsonValueKind.False,
            GameVariableType.Int => kind == JsonValueKind.Number
                && tryReadNumber(value, out double integer)
                && integer == Math.Truncate(integer)
                && integer is >= int.MinValue and <= int.MaxValue,
            GameVariableType.Float => kind == JsonValueKind.Number
                && tryReadNumber(value, out double number)
                && double.IsFinite(number),
            GameVariableType.String => kind == JsonValueKind.String,
            GameVariableType.List => value is JsonArray,
            GameVariableType.Dict => value is JsonObject,
            _ => false,
        };
        if (!valid)
            throw new InvalidDataException($"Initial value does not match {type}");
        validateJsonData(value);
    }

    private static void validateJsonData(JsonNode value)
    {
        if (value is JsonArray array)
        {
            foreach (JsonNode? item in array)
            {
                if (item is null)
                    throw new InvalidDataException("Initial values cannot contain nil entries");
                validateJsonData(item);
            }
            return;
        }
        if (value is JsonObject dictionary)
        {
            foreach (KeyValuePair<string, JsonNode?> pair in dictionary)
            {
                if (pair.Value is null)
                    throw new InvalidDataException("Initial values cannot contain nil entries");
                validateJsonData(pair.Value);
            }
            return;
        }
        JsonValueKind kind = value.GetValueKind();
        if (kind == JsonValueKind.Number
            && (!tryReadNumber(value, out double number) || !double.IsFinite(number)))
        {
            throw new InvalidDataException("Initial values must contain finite numbers");
        }
        if (kind is not JsonValueKind.Number
            and not JsonValueKind.String
            and not JsonValueKind.True
            and not JsonValueKind.False)
        {
            throw new InvalidDataException("Initial values contain unsupported data");
        }
    }

    private string renderRuntime()
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker).Append("\n\nreturn {\n");
        foreach (GameVariableDefinition definition in variables.OrderBy(
            value => value.Name,
            StringComparer.Ordinal))
        {
            JsonNode? initialValue = definition.InitialValue;
            if (initialValue is null)
                throw new InvalidDataException($"Initial value for {definition.Name} is required");
            builder.Append("    [").Append(quote(definition.Name)).Append("] = ");
            appendInitialValue(builder, initialValue, definition.Type);
            builder.Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private string renderMetadata()
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker)
            .Append("\n\nlocal _METADATA = {\n")
            .Append("    GameVariables = {\n")
            .Append("        attrs = {\n");
        foreach (GameVariableDefinition definition in variables.OrderBy(
            value => value.Name,
            StringComparer.Ordinal))
            builder.Append("            ").Append(quote(definition.Name)).Append(",\n");
        builder.Append("        },\n");
        foreach (GameVariableDefinition definition in variables.OrderBy(
            value => value.Name,
            StringComparer.Ordinal))
        {
            builder.Append("        [")
                .Append(quote(definition.Name))
                .Append("] = {\n")
                .Append("            type = ")
                .Append(quote(typeName(definition.Type)))
                .Append(",\n");
            if (definition.Remark.Length != 0)
            {
                builder.Append("            Meta = {\n")
                    .Append("                Remark = ")
                    .Append(quote(definition.Remark))
                    .Append(",\n")
                    .Append("            },\n");
            }
            builder.Append("        },\n");
        }
        builder.Append("    },\n}\n\nreturn _METADATA\n");
        return builder.ToString();
    }

    private static void appendLuaValue(StringBuilder builder, JsonNode value, int indent)
    {
        if (value is JsonArray array)
        {
            appendLuaArray(builder, array, indent);
            return;
        }
        if (value is JsonObject dictionary)
        {
            appendLuaObject(builder, dictionary, indent);
            return;
        }
        switch (value.GetValueKind())
        {
            case JsonValueKind.True:
                builder.Append("true");
                return;
            case JsonValueKind.False:
                builder.Append("false");
                return;
            case JsonValueKind.String:
                builder.Append(quote(value.GetValue<string>()));
                return;
            case JsonValueKind.Number:
                if (tryReadNumber(value, out double number) && double.IsFinite(number))
                {
                    builder.Append(number.ToString("R", CultureInfo.InvariantCulture));
                    return;
                }
                break;
        }
        throw new InvalidDataException("Initial value contains unsupported data");
    }

    private static void appendInitialValue(
        StringBuilder builder,
        JsonNode value,
        GameVariableType type)
    {
        if (type == GameVariableType.Float
            && value.GetValueKind() == JsonValueKind.Number
            && tryReadNumber(value, out double number)
            && double.IsFinite(number))
        {
            string text = number.ToString("R", CultureInfo.InvariantCulture);
            if (number == Math.Truncate(number)
                && !text.Contains('.', StringComparison.Ordinal)
                && !text.Contains('E', StringComparison.OrdinalIgnoreCase))
            {
                text += ".0";
            }
            builder.Append(text);
            return;
        }
        appendLuaValue(builder, value, 1);
    }

    private static void appendLuaArray(StringBuilder builder, JsonArray array, int indent)
    {
        if (array.Count == 0)
        {
            builder.Append("{}");
            return;
        }
        builder.Append("{\n");
        foreach (JsonNode? item in array)
        {
            if (item is null)
                throw new InvalidDataException("Initial values cannot contain nil entries");
            appendIndent(builder, indent + 1);
            appendLuaValue(builder, item, indent + 1);
            builder.Append(",\n");
        }
        appendIndent(builder, indent);
        builder.Append('}');
    }

    private static void appendLuaObject(StringBuilder builder, JsonObject dictionary, int indent)
    {
        if (dictionary.Count == 0)
        {
            builder.Append("{}");
            return;
        }
        builder.Append("{\n");
        foreach (KeyValuePair<string, JsonNode?> pair in dictionary.OrderBy(
            value => value.Key,
            StringComparer.Ordinal))
        {
            if (pair.Value is null)
                throw new InvalidDataException("Initial values cannot contain nil entries");
            appendIndent(builder, indent + 1);
            builder.Append('[').Append(quote(pair.Key)).Append("] = ");
            appendLuaValue(builder, pair.Value, indent + 1);
            builder.Append(",\n");
        }
        appendIndent(builder, indent);
        builder.Append('}');
    }

    private static void appendIndent(StringBuilder builder, int indent)
    {
        builder.Append(' ', indent * 4);
    }

    private static string quote(string value)
    {
        StringBuilder builder = new(value.Length + 2);
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (char.IsControl(character) && character <= byte.MaxValue)
                        builder.Append('\\').Append(((int)character).ToString("D3", CultureInfo.InvariantCulture));
                    else
                        builder.Append(character);
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private void writePair(string runtimeText, string metadataText)
    {
        string directory = Path.GetDirectoryName(RuntimePath)
            ?? throw new InvalidOperationException(RuntimePath);
        Directory.CreateDirectory(directory);
        ensureOwnedIfPresent(RuntimePath);
        ensureOwnedIfPresent(MetadataPath);
        byte[]? runtimeOriginal = File.Exists(RuntimePath) ? File.ReadAllBytes(RuntimePath) : null;
        string runtimeTemp = createTempPath(RuntimePath);
        string metadataTemp = createTempPath(MetadataPath);
        bool runtimeReplaced = false;
        try
        {
            writeDurable(runtimeTemp, runtimeText);
            writeDurable(metadataTemp, metadataText);
            File.Move(runtimeTemp, RuntimePath, true);
            runtimeReplaced = true;
            File.Move(metadataTemp, MetadataPath, true);
        }
        catch (Exception exception) when (isFileException(exception))
        {
            if (runtimeReplaced)
            {
                try
                {
                    restore(RuntimePath, runtimeOriginal);
                }
                catch (Exception rollbackException) when (isFileException(rollbackException))
                {
                    throw new IOException(
                        exception.Message + "; rollback failed: " + rollbackException.Message,
                        exception);
                }
            }
            throw;
        }
        finally
        {
            deleteTemp(runtimeTemp);
            deleteTemp(metadataTemp);
        }
    }

    private static void restore(string path, byte[]? original)
    {
        if (original is null)
        {
            File.Delete(path);
            return;
        }
        string temp = createTempPath(path);
        try
        {
            writeDurable(temp, original);
            File.Move(temp, path, true);
        }
        finally
        {
            deleteTemp(temp);
        }
    }

    private static void writeDurable(string path, string text)
    {
        writeDurable(path, utf8.GetBytes(text));
    }

    private static void writeDurable(string path, byte[] bytes)
    {
        using FileStream stream = new(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
        stream.Write(bytes);
        stream.Flush(true);
    }

    private static string createTempPath(string path)
    {
        string directory = Path.GetDirectoryName(path) ?? throw new InvalidOperationException(path);
        return Path.Combine(directory, "." + Path.GetFileName(path) + "." + Guid.NewGuid().ToString("N") + ".tmp");
    }

    private static void deleteTemp(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    private static void ensureOwnedIfPresent(string path)
    {
        if (File.Exists(path))
            ensureOwned(path);
    }

    private static void ensureOwned(string path)
    {
        using StreamReader reader = new(path, utf8, true);
        string? firstLine = reader.ReadLine();
        if (!string.Equals(firstLine, GeneratedMarker, StringComparison.Ordinal))
            throw new InvalidDataException($"{path} is not owned by the game variable manager");
    }

    private static void ensureMarker(string text, string path)
    {
        int newline = text.IndexOf('\n');
        string firstLine = newline < 0 ? text : text[..newline].TrimEnd('\r');
        if (!string.Equals(firstLine, GeneratedMarker, StringComparison.Ordinal))
            throw new InvalidDataException($"{path} is not owned by the game variable manager");
    }

    private void ensureEquivalent(IReadOnlyList<GameVariableDefinition> parsed)
    {
        if (parsed.Count != variables.Count)
            throw new InvalidDataException("Generated game variable files failed validation");
        for (int index = 0; index < variables.Count; index += 1)
        {
            GameVariableDefinition expected = variables[index];
            GameVariableDefinition actual = parsed[index];
            if (!string.Equals(expected.Name, actual.Name, StringComparison.Ordinal)
                || expected.Type != actual.Type
                || !valuesEquivalent(expected.InitialValue, actual.InitialValue)
                || !string.Equals(expected.Remark, actual.Remark, StringComparison.Ordinal))
            {
                throw new InvalidDataException("Generated game variable files failed validation");
            }
        }
    }

    private static bool tryReadNumber(JsonNode value, out double result)
    {
        if (value is not JsonValue json)
        {
            result = 0;
            return false;
        }
        if (json.TryGetValue(out double doubleValue))
        {
            result = doubleValue;
            return true;
        }
        if (json.TryGetValue(out float floatValue))
        {
            result = floatValue;
            return true;
        }
        if (json.TryGetValue(out decimal decimalValue))
        {
            result = (double)decimalValue;
            return true;
        }
        if (json.TryGetValue(out long longValue))
        {
            result = longValue;
            return true;
        }
        if (json.TryGetValue(out ulong unsignedValue))
        {
            result = unsignedValue;
            return true;
        }
        if (json.TryGetValue(out int intValue))
        {
            result = intValue;
            return true;
        }
        if (json.TryGetValue(out uint uintValue))
        {
            result = uintValue;
            return true;
        }
        if (json.TryGetValue(out short shortValue))
        {
            result = shortValue;
            return true;
        }
        if (json.TryGetValue(out ushort ushortValue))
        {
            result = ushortValue;
            return true;
        }
        if (json.TryGetValue(out byte byteValue))
        {
            result = byteValue;
            return true;
        }
        if (json.TryGetValue(out sbyte sbyteValue))
        {
            result = sbyteValue;
            return true;
        }
        if (json.TryGetValue(out JsonElement element)
            && element.ValueKind == JsonValueKind.Number
            && element.TryGetDouble(out result))
        {
            return true;
        }
        result = 0;
        return false;
    }

    private static JsonNode createDefault(GameVariableType type)
    {
        return type switch
        {
            GameVariableType.Bool => JsonValue.Create(false),
            GameVariableType.Int => JsonValue.Create(0),
            GameVariableType.Float => JsonValue.Create(0.0),
            GameVariableType.String => JsonValue.Create(string.Empty),
            GameVariableType.List => new JsonArray(),
            GameVariableType.Dict => new JsonObject(),
            _ => throw new InvalidDataException("Unsupported game variable type"),
        };
    }

    private static bool valuesEquivalent(JsonNode? left, JsonNode? right)
    {
        if (JsonNode.DeepEquals(left, right))
            return true;
        if (left is null || right is null)
            return false;
        if (left is JsonArray leftArray && right is JsonArray rightArray)
        {
            if (leftArray.Count != rightArray.Count)
                return false;
            for (int index = 0; index < leftArray.Count; index += 1)
            {
                if (!valuesEquivalent(leftArray[index], rightArray[index]))
                    return false;
            }
            return true;
        }
        if (left is JsonObject leftObject && right is JsonObject rightObject)
        {
            if (leftObject.Count != rightObject.Count)
                return false;
            foreach (KeyValuePair<string, JsonNode?> pair in leftObject)
            {
                if (!rightObject.TryGetPropertyValue(pair.Key, out JsonNode? rightValue)
                    || !valuesEquivalent(pair.Value, rightValue))
                {
                    return false;
                }
            }
            return true;
        }
        return left is JsonArray { Count: 0 } && right is JsonObject { Count: 0 }
            || left is JsonObject { Count: 0 } && right is JsonArray { Count: 0 };
    }

    private static string typeName(GameVariableType type)
    {
        return type switch
        {
            GameVariableType.Bool => "bool",
            GameVariableType.Int => "int",
            GameVariableType.Float => "float",
            GameVariableType.String => "string",
            GameVariableType.List => "any[]",
            GameVariableType.Dict => "Dict[string, any]",
            _ => throw new InvalidDataException("Unsupported game variable type"),
        };
    }

    private static bool tryParseType(string value, out GameVariableType type)
    {
        switch (value)
        {
            case "bool":
                type = GameVariableType.Bool;
                return true;
            case "int":
                type = GameVariableType.Int;
                return true;
            case "float":
                type = GameVariableType.Float;
                return true;
            case "string":
                type = GameVariableType.String;
                return true;
            case "any[]":
                type = GameVariableType.List;
                return true;
            case "Dict[string, any]":
                type = GameVariableType.Dict;
                return true;
            default:
                type = default;
                return false;
        }
    }

    private static string formatFailure(Exception exception)
    {
        return "GameVariables(" + exception.Message + ")";
    }

    private static bool isSaveException(Exception exception)
    {
        return isFileException(exception)
            || exception is InvalidDataException
            || exception is InterpreterException
            || exception is ArgumentException
            || exception is NotSupportedException;
    }

    private static bool isFileException(Exception exception)
    {
        return exception is IOException
            or UnauthorizedAccessException
            or SecurityException;
    }

    private sealed record MetadataEntry(string Name, GameVariableType Type, string Remark);
}
