using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace Ludork.Services;

internal sealed record GeneralEnumSaveResult(
    bool Success,
    IReadOnlyList<string> ChangedPaths,
    string Detail);

internal sealed class GeneralEnumService
{
    internal const string RuntimeRelativePath = "Scripts/Source/Configs/GeneralEnum.lua";
    internal const string StubRelativePath = "Scripts/stub/Source/Configs/GeneralEnum.d.lua";
    internal const string TypesRuntimeRelativePath = "Scripts/Source/Configs/GeneralDataTypes.lua";
    internal const string TypesStubRelativePath = "Scripts/stub/Source/Configs/GeneralDataTypes.d.lua";
    private const string GeneratedMarker = "-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.";
    private const string AttributeSetModule = "Global.Gameplay.AttributeSet";
    private static readonly UTF8Encoding utf8 = new(false, true);
    private static readonly HashSet<string> luaKeywords = new(StringComparer.Ordinal)
    {
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "global", "goto", "if",
        "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
    };

    public GeneralEnumService(string projectPath)
    {
        RuntimePath = Path.Combine(projectPath, RuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        StubPath = Path.Combine(projectPath, StubRelativePath.Replace('/', Path.DirectorySeparatorChar));
        TypesRuntimePath = Path.Combine(
            projectPath,
            TypesRuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        TypesStubPath = Path.Combine(
            projectPath,
            TypesStubRelativePath.Replace('/', Path.DirectorySeparatorChar));
    }

    public string RuntimePath { get; }
    public string StubPath { get; }
    public string TypesRuntimePath { get; }
    public string TypesStubPath { get; }

    public GeneralEnumSaveResult Save(IReadOnlyDictionary<string, JsonObject> generalData)
    {
        try
        {
            IReadOnlyList<GeneralEnumType> types = buildTypes(generalData);
            string runtimeText = renderRuntime(types);
            string stubText = renderStub(types);
            string typesRuntimeText = renderTypesRuntime(types);
            string typesStubText = renderTypesStub(types);
            GeneratedOutput[] outputs =
            [
                new GeneratedOutput(RuntimeRelativePath, RuntimePath, runtimeText),
                new GeneratedOutput(StubRelativePath, StubPath, stubText),
                new GeneratedOutput(TypesRuntimeRelativePath, TypesRuntimePath, typesRuntimeText),
                new GeneratedOutput(TypesStubRelativePath, TypesStubPath, typesStubText),
            ];
            string[] changedPaths = outputs
                .Where(output => !contentEquals(output.Path, output.Content))
                .Select(output => output.RelativePath)
                .ToArray();
            if (changedPaths.Length == 0)
                return new GeneralEnumSaveResult(true, [], string.Empty);
            writeOutputs(outputs);
            return new GeneralEnumSaveResult(true, changedPaths, string.Empty);
        }
        catch (Exception exception) when (isSaveException(exception))
        {
            return new GeneralEnumSaveResult(false, [], exception.Message);
        }
    }

    private static IReadOnlyList<GeneralEnumType> buildTypes(IReadOnlyDictionary<string, JsonObject> generalData)
    {
        HashSet<string> usedTypeNames = new(StringComparer.Ordinal) { "GeneralDataKey" };
        List<GeneralEnumType> result = [];
        foreach (KeyValuePair<string, JsonObject> entry in generalData
            .Where(entry => entry.Key.Length != 0)
            .OrderBy(entry => entry.Key, StringComparer.Ordinal))
        {
            string typeName = uniqueIdentifier(toTypeIdentifier(entry.Key), usedTypeNames);
            HashSet<string> usedMemberNames = new(StringComparer.Ordinal);
            List<GeneralEnumMember> members = [];
            if (entry.Value["members"] is JsonObject memberData)
            {
                foreach (string memberKey in memberData.Select(member => member.Key)
                    .Where(key => key.Length != 0)
                    .OrderBy(key => key, StringComparer.Ordinal))
                {
                    string memberName = uniqueIdentifier(toMemberIdentifier(memberKey), usedMemberNames);
                    members.Add(new GeneralEnumMember(memberKey, memberName));
                }
            }
            List<GeneralDataAttribute> attributes = [];
            if (entry.Value["params"] is JsonObject parameters)
            {
                foreach (KeyValuePair<string, JsonNode?> parameterEntry in parameters)
                {
                    if (parameterEntry.Value is not JsonObject definition)
                    {
                        throw new InvalidDataException(
                            $"General Data parameter {entry.Key}.{parameterEntry.Key} must be an object");
                    }
                    string? attributeType = definition["type"]?.GetValue<string>();
                    if (string.IsNullOrWhiteSpace(attributeType)
                        || !definition.TryGetPropertyValue("defaultValue", out JsonNode? defaultValue))
                    {
                        throw new InvalidDataException(
                            $"General Data parameter {entry.Key}.{parameterEntry.Key} requires type and defaultValue");
                    }
                    attributes.Add(new GeneralDataAttribute(
                        parameterEntry.Key,
                        attributeType,
                        defaultValue?.DeepClone(),
                        definition["itemType"]?.GetValue<string>(),
                        definition["valueType"]?.GetValue<string>()));
                }
            }
            result.Add(new GeneralEnumType(entry.Key, typeName, typeName + "AttributeSet", members, attributes));
        }
        return result;
    }

    private static string renderRuntime(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker).Append("\n\n");
        appendRuntimeTable(
            builder,
            "GeneralDataKey",
            types.Select(type => new GeneralEnumMember(type.SourceKey, type.TypeName)));
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendRuntimeTable(builder, type.TypeName, type.Members);
        }
        builder.Append("\nreturn {\n")
            .Append("    GeneralDataKey = GeneralDataKey,\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append("    ")
                .Append(type.TypeName)
                .Append(" = ")
                .Append(type.TypeName)
                .Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private static string renderStub(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append("---@meta Source.Configs.GeneralEnum\n")
            .Append("--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.\n")
            .Append("--- @brief General Data key constants.\n\n");
        appendStubType(
            builder,
            "GeneralDataKey",
            "General Data table keys.",
            types.Select(type => new GeneralEnumMember(type.SourceKey, type.TypeName)));
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendStubType(builder, type.TypeName, type.SourceKey + " member keys.", type.Members);
        }
        builder.Append("\nreturn {\n")
            .Append("    GeneralDataKey = GeneralDataKey,\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append("    ")
                .Append(type.TypeName)
                .Append(" = ")
                .Append(type.TypeName)
                .Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private static string renderTypesRuntime(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker)
            .Append("\nlocal AttributeSet = require(")
            .Append(quote(AttributeSetModule))
            .Append(")\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendAttributeSetRuntime(builder, type);
        }
        builder.Append("\nlocal Types = {\n");
        for (int index = 0; index < types.Count; index++)
        {
            GeneralEnumType type = types[index];
            builder.Append("    [")
                .Append(quote(type.SourceKey))
                .Append("] = ")
                .Append(type.AttributeSetName);
            if (index != types.Count - 1)
                builder.Append(',');
            builder.Append('\n');
        }
        builder.Append("}\n\nlocal GeneralDataTypes = {\n")
            .Append("    Types = Types,\n");
        for (int index = 0; index < types.Count; index++)
        {
            GeneralEnumType type = types[index];
            builder.Append("    ")
                .Append(type.AttributeSetName)
                .Append(" = ")
                .Append(type.AttributeSetName);
            if (index != types.Count - 1)
                builder.Append(',');
            builder.Append('\n');
        }
        builder.Append("}\n\n")
            .Append("function GeneralDataTypes.Create(typeName, memberId, memberData)\n")
            .Append("    assert(rawget(Types, typeName) ~= nil, \"General Data type not found: \" .. tostring(typeName))\n")
            .Append("    local attributeType = Types[typeName]\n")
            .Append("    assert(type(memberId) == \"string\", \"General Data member ID must be a string\")\n")
            .Append("    assert(type(memberData) == \"table\", \"General Data member must be a table\")\n")
            .Append("    ---@type table<string, any>\n")
            .Append("    local values = { ID = deepcopy(memberId) }\n")
            .Append("    for _, name in ipairs(attributeType.ATTRIBUTE_NAMES) do\n")
            .Append("        local value = rawget(memberData, name)\n")
            .Append("        if value == nil then\n")
            .Append("            value = attributeType.SCHEMA[name].default\n")
            .Append("        end\n")
            .Append("        values[name] = deepcopy(value)\n")
            .Append("    end\n")
            .Append("    return attributeType.new(values)\n")
            .Append("end\n\n")
            .Append("return GeneralDataTypes\n");
        return builder.ToString();
    }

    private static void appendAttributeSetRuntime(StringBuilder builder, GeneralEnumType type)
    {
        builder.Append("local ").Append(type.AttributeSetName).Append(" = {}\n");
        if (type.Attributes.Count == 0)
        {
            builder.Append(type.AttributeSetName).Append(".ATTRIBUTE_NAMES = {}\n");
        }
        else
        {
            string names = string.Join(", ", type.Attributes.Select(attribute => quote(attribute.Name)));
            string singleLine = type.AttributeSetName + ".ATTRIBUTE_NAMES = { " + names + " }";
            if (singleLine.Length <= 120)
            {
                builder.Append(singleLine).Append('\n');
            }
            else
            {
                builder.Append(type.AttributeSetName)
                    .Append(".ATTRIBUTE_NAMES = {\n    ")
                    .Append(names)
                    .Append("\n}\n");
            }
        }
        builder.Append(type.AttributeSetName).Append(".SCHEMA = {");
        if (type.Attributes.Count == 0)
        {
            builder.Append("}\n");
        }
        else
        {
            builder.Append('\n');
            for (int index = 0; index < type.Attributes.Count; index++)
            {
                GeneralDataAttribute attribute = type.Attributes[index];
                builder.Append("    ");
                appendLuaTableKey(builder, attribute.Name);
                builder.Append(" = { type = ")
                    .Append(quote(attribute.Type))
                    .Append(", default = ");
                appendLuaValue(builder, attribute.DefaultValue);
                builder.Append(" }");
                if (index != type.Attributes.Count - 1)
                    builder.Append(',');
                builder.Append('\n');
            }
            builder.Append("}\n");
        }
        builder.Append(type.AttributeSetName)
            .Append(" = class(")
            .Append(type.AttributeSetName)
            .Append(", AttributeSet)\n");
    }

    private static string renderTypesStub(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append("---@meta Source.Configs.GeneralDataTypes\n")
            .Append("--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.\n\n");
        foreach (GeneralEnumType type in types)
        {
            string qualifiedName = "Source.Configs.GeneralDataTypes." + type.AttributeSetName;
            builder.Append("---@class ").Append(qualifiedName).Append(": Global.Gameplay.AttributeSet\n");
            List<LuaDocField> fields =
            [
                new LuaDocField("ID", "string"),
                new LuaDocField("ATTRIBUTE_NAMES", "string[]"),
                new LuaDocField("SCHEMA", "table<string, Global.Gameplay.AttributeSchema>"),
            ];
            foreach (GeneralDataAttribute attribute in type.Attributes)
                fields.Add(new LuaDocField(luaDocFieldName(attribute.Name), luaDocType(attribute)));
            appendAlignedLuaDocFields(builder, fields);
            builder.Append("---@type ")
                .Append(qualifiedName)
                .Append(" & Class.ClassType<")
                .Append(qualifiedName)
                .Append(">\n")
                .Append("local ")
                .Append(type.AttributeSetName)
                .Append(" = {}\n\n");
        }
        builder.Append("---@class Source.Configs.GeneralDataTypes.Module\n");
        List<LuaDocField> moduleFields =
        [
            new LuaDocField("Types", "table<string, Class.ClassType<Global.Gameplay.AttributeSet>>"),
        ];
        foreach (GeneralEnumType type in types)
        {
            string qualifiedName = "Source.Configs.GeneralDataTypes." + type.AttributeSetName;
            moduleFields.Add(new LuaDocField(
                type.AttributeSetName,
                qualifiedName + " & Class.ClassType<" + qualifiedName + ">"));
        }
        appendAlignedLuaDocFields(builder, moduleFields);
        builder.Append("local GeneralDataTypes = {}\n\n");
        appendAlignedLuaDocParameters(
            builder,
            [
                new LuaDocField("typeName", "string"),
                new LuaDocField("memberId", "string"),
                new LuaDocField("memberData", "table<string, any>"),
            ]);
        builder
            .Append("---@return Global.Gameplay.AttributeSet\n")
            .Append("function GeneralDataTypes.Create(typeName, memberId, memberData) end\n\n")
            .Append("return GeneralDataTypes\n");
        return builder.ToString();
    }

    private static void appendAlignedLuaDocFields(StringBuilder builder, IReadOnlyList<LuaDocField> fields)
    {
        int width = fields.Max(field => field.Name.Length);
        foreach (LuaDocField field in fields)
        {
            builder.Append("---@field ")
                .Append(field.Name.PadRight(width))
                .Append(' ')
                .Append(field.Type)
                .Append('\n');
        }
    }

    private static void appendAlignedLuaDocParameters(StringBuilder builder, IReadOnlyList<LuaDocField> parameters)
    {
        int width = parameters.Max(parameter => parameter.Name.Length);
        foreach (LuaDocField parameter in parameters)
        {
            builder.Append("---@param ")
                .Append(parameter.Name.PadRight(width))
                .Append(' ')
                .Append(parameter.Type)
                .Append('\n');
        }
    }

    private static string luaDocType(GeneralDataAttribute attribute)
    {
        return attribute.Type switch
        {
            "bool" => "boolean",
            "int" => "integer",
            "float" => "number",
            "string" or "file" => "string",
            "list" => luaDocScalarType(attribute.ItemType) + "[]",
            "dict" => "table<string, " + luaDocScalarType(attribute.ValueType) + ">",
            _ => luaDocScalarType(attribute.Type),
        };
    }

    private static string luaDocScalarType(string? type)
    {
        return type switch
        {
            "bool" => "boolean",
            "int" => "integer",
            "float" => "number",
            "string" or "file" => "string",
            null or "" or "any" => "any",
            _ => type,
        };
    }

    private static string luaDocFieldName(string name)
    {
        return isLuaIdentifier(name) ? name : "[" + quote(name) + "]";
    }

    private static void appendLuaTableKey(StringBuilder builder, string key)
    {
        if (isLuaIdentifier(key))
            builder.Append(key);
        else
            builder.Append('[').Append(quote(key)).Append(']');
    }

    private static bool isLuaIdentifier(string value)
    {
        if (value.Length == 0 || luaKeywords.Contains(value)
            || value[0] != '_' && !char.IsLetter(value[0]))
        {
            return false;
        }
        return value.Skip(1).All(character => character == '_' || char.IsLetterOrDigit(character));
    }

    private static void appendLuaValue(StringBuilder builder, JsonNode? value)
    {
        if (value is null)
        {
            builder.Append("nil");
            return;
        }
        if (value is JsonArray array)
        {
            builder.Append('{');
            for (int index = 0; index < array.Count; index++)
            {
                if (index != 0)
                    builder.Append(", ");
                appendLuaValue(builder, array[index]);
            }
            builder.Append('}');
            return;
        }
        if (value is JsonObject obj)
        {
            builder.Append('{');
            int index = 0;
            foreach (KeyValuePair<string, JsonNode?> entry in obj)
            {
                if (index != 0)
                    builder.Append(", ");
                appendLuaTableKey(builder, entry.Key);
                builder.Append(" = ");
                appendLuaValue(builder, entry.Value);
                index++;
            }
            builder.Append('}');
            return;
        }
        JsonValue scalar = (JsonValue)value;
        if (scalar.TryGetValue(out string? stringValue))
            builder.Append(quote(stringValue));
        else if (scalar.TryGetValue(out bool boolValue))
            builder.Append(boolValue ? "true" : "false");
        else if (scalar.TryGetValue(out long longValue))
            builder.Append(longValue.ToString(CultureInfo.InvariantCulture));
        else if (scalar.TryGetValue(out double doubleValue))
            builder.Append(doubleValue.ToString("R", CultureInfo.InvariantCulture));
        else
            throw new InvalidDataException("Unsupported General Data default value");
    }

    private static void appendRuntimeTable(
        StringBuilder builder,
        string tableName,
        IEnumerable<GeneralEnumMember> entries)
    {
        GeneralEnumMember[] values = entries.ToArray();
        if (values.Length == 0)
        {
            builder.Append("local ").Append(tableName).Append(" = {}\n");
            return;
        }
        builder.Append("local ").Append(tableName).Append(" = {\n");
        foreach (GeneralEnumMember entry in values)
        {
            builder.Append("    ")
                .Append(entry.Identifier)
                .Append(" = ")
                .Append(quote(entry.SourceKey))
                .Append(",\n");
        }
        builder.Append("}\n");
    }

    private static void appendStubType(
        StringBuilder builder,
        string typeName,
        string description,
        IEnumerable<GeneralEnumMember> entries)
    {
        builder.Append("--- @brief ").Append(description).Append("\n")
            .Append("---@class Source.Configs.GeneralEnum.").Append(typeName).Append("\n");
        foreach (GeneralEnumMember entry in entries)
            builder.Append("---@field ").Append(entry.Identifier).Append(" string\n");
        builder.Append("---@type Source.Configs.GeneralEnum.").Append(typeName).Append("\n")
            .Append("local ").Append(typeName).Append(" = {}\n");
    }

    private static string toTypeIdentifier(string value)
    {
        string[] parts = Regex.Split(value, "[^0-9A-Za-z]+")
            .Where(part => part.Length != 0)
            .ToArray();
        string result = string.Concat(parts.Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
        if (result.Length == 0)
            result = "GeneralData";
        if (char.IsDigit(result[0]))
            result = "GeneralData" + result;
        if (luaKeywords.Contains(result))
            result += "Data";
        return result;
    }

    private static string toMemberIdentifier(string value)
    {
        string result = Regex.Replace(value, "[^0-9A-Za-z_]", "_").Trim('_');
        if (result.Length == 0)
            result = "Key";
        if (char.IsDigit(result[0]))
            result = "_" + result;
        if (luaKeywords.Contains(result))
            result += "_";
        return result;
    }

    private static string uniqueIdentifier(string value, HashSet<string> usedNames)
    {
        string candidate = value;
        int suffix = 2;
        while (!usedNames.Add(candidate))
            candidate = value + "_" + suffix++;
        return candidate;
    }

    private static string quote(string value)
    {
        StringBuilder builder = new(value.Length + 2);
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (char.IsControl(character) && character <= byte.MaxValue)
                        builder.Append('\\').Append(((int)character).ToString("D3", CultureInfo.InvariantCulture));
                    else
                        builder.Append(character);
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private static bool contentEquals(string path, string expected)
    {
        return File.Exists(path)
            && string.Equals(File.ReadAllText(path, utf8), expected, StringComparison.Ordinal);
    }

    private static void writeOutputs(IReadOnlyList<GeneratedOutput> outputs)
    {
        Dictionary<string, byte[]?> originals = new(StringComparer.Ordinal);
        Dictionary<string, string> temporaryPaths = new(StringComparer.Ordinal);
        foreach (GeneratedOutput output in outputs)
        {
            string directory = Path.GetDirectoryName(output.Path)
                ?? throw new InvalidOperationException(output.Path);
            Directory.CreateDirectory(directory);
            originals[output.Path] = File.Exists(output.Path) ? File.ReadAllBytes(output.Path) : null;
            temporaryPaths[output.Path] = createTemporaryPath(output.Path);
        }
        try
        {
            foreach (GeneratedOutput output in outputs)
                writeDurable(temporaryPaths[output.Path], utf8.GetBytes(output.Content));
            foreach (GeneratedOutput output in outputs)
                File.Move(temporaryPaths[output.Path], output.Path, true);
        }
        catch (Exception exception) when (isFileException(exception))
        {
            try
            {
                foreach (GeneratedOutput output in outputs)
                    restore(output.Path, originals[output.Path]);
            }
            catch (Exception rollbackException) when (isFileException(rollbackException))
            {
                throw new IOException(
                    exception.Message + "; rollback failed: " + rollbackException.Message,
                    exception);
            }
            throw;
        }
        finally
        {
            foreach (string temporaryPath in temporaryPaths.Values)
                deleteTemporary(temporaryPath);
        }
    }

    private static void restore(string path, byte[]? content)
    {
        if (content is null)
        {
            File.Delete(path);
            return;
        }
        string temporary = createTemporaryPath(path);
        try
        {
            writeDurable(temporary, content);
            File.Move(temporary, path, true);
        }
        finally
        {
            deleteTemporary(temporary);
        }
    }

    private static void writeDurable(string path, byte[] content)
    {
        using FileStream stream = new(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
        stream.Write(content);
        stream.Flush(true);
    }

    private static string createTemporaryPath(string path)
    {
        string directory = Path.GetDirectoryName(path) ?? throw new InvalidOperationException(path);
        return Path.Combine(directory, "." + Path.GetFileName(path) + "." + Guid.NewGuid().ToString("N") + ".tmp");
    }

    private static void deleteTemporary(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    private static bool isSaveException(Exception exception)
    {
        return isFileException(exception) || exception is InvalidDataException or InvalidOperationException;
    }

    private static bool isFileException(Exception exception)
    {
        return exception is IOException or UnauthorizedAccessException or SecurityException or DecoderFallbackException;
    }

    private sealed record GeneralEnumType(
        string SourceKey,
        string TypeName,
        string AttributeSetName,
        IReadOnlyList<GeneralEnumMember> Members,
        IReadOnlyList<GeneralDataAttribute> Attributes);

    private sealed record GeneralEnumMember(string SourceKey, string Identifier);

    private sealed record GeneralDataAttribute(
        string Name,
        string Type,
        JsonNode? DefaultValue,
        string? ItemType,
        string? ValueType);

    private sealed record LuaDocField(string Name, string Type);

    private sealed record GeneratedOutput(string RelativePath, string Path, string Content);
}
