using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace Ludork.Services;

internal sealed record GeneralEnumSaveResult(bool Success, bool Changed, string Detail);

internal sealed class GeneralEnumService
{
    internal const string RuntimeRelativePath = "Scripts/Source/Configs/GeneralEnum.lua";
    internal const string StubRelativePath = "Scripts/stub/Source/Configs/GeneralEnum.d.lua";
    private const string GeneratedMarker = "-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.";
    private static readonly UTF8Encoding utf8 = new(false, true);
    private static readonly HashSet<string> luaKeywords = new(StringComparer.Ordinal)
    {
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "global", "goto", "if",
        "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
    };

    public GeneralEnumService(string projectPath)
    {
        RuntimePath = Path.Combine(projectPath, RuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        StubPath = Path.Combine(projectPath, StubRelativePath.Replace('/', Path.DirectorySeparatorChar));
    }

    public string RuntimePath { get; }
    public string StubPath { get; }

    public GeneralEnumSaveResult Save(IReadOnlyDictionary<string, JsonObject> generalData)
    {
        try
        {
            IReadOnlyList<GeneralEnumType> types = buildTypes(generalData);
            string runtimeText = renderRuntime(types);
            string stubText = renderStub(types);
            if (contentEquals(RuntimePath, runtimeText) && contentEquals(StubPath, stubText))
                return new GeneralEnumSaveResult(true, false, string.Empty);
            writePair(runtimeText, stubText);
            return new GeneralEnumSaveResult(true, true, string.Empty);
        }
        catch (Exception exception) when (isFileException(exception))
        {
            return new GeneralEnumSaveResult(false, false, exception.Message);
        }
    }

    private static IReadOnlyList<GeneralEnumType> buildTypes(IReadOnlyDictionary<string, JsonObject> generalData)
    {
        HashSet<string> usedTypeNames = new(StringComparer.Ordinal) { "GeneralDataKey" };
        List<GeneralEnumType> result = [];
        foreach (KeyValuePair<string, JsonObject> entry in generalData
            .Where(entry => entry.Key.Length != 0)
            .OrderBy(entry => entry.Key, StringComparer.Ordinal))
        {
            string typeName = uniqueIdentifier(toTypeIdentifier(entry.Key), usedTypeNames);
            HashSet<string> usedMemberNames = new(StringComparer.Ordinal);
            List<GeneralEnumMember> members = [];
            if (entry.Value["members"] is JsonObject memberData)
            {
                foreach (string memberKey in memberData.Select(member => member.Key)
                    .Where(key => key.Length != 0)
                    .OrderBy(key => key, StringComparer.Ordinal))
                {
                    string memberName = uniqueIdentifier(toMemberIdentifier(memberKey), usedMemberNames);
                    members.Add(new GeneralEnumMember(memberKey, memberName));
                }
            }
            result.Add(new GeneralEnumType(entry.Key, typeName, members));
        }
        return result;
    }

    private static string renderRuntime(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker).Append("\n\n");
        appendRuntimeTable(
            builder,
            "GeneralDataKey",
            types.Select(type => new GeneralEnumMember(type.SourceKey, type.TypeName)));
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendRuntimeTable(builder, type.TypeName, type.Members);
        }
        builder.Append("\nreturn {\n")
            .Append("    GeneralDataKey = GeneralDataKey,\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append("    ")
                .Append(type.TypeName)
                .Append(" = ")
                .Append(type.TypeName)
                .Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private static string renderStub(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append("---@meta Source.Configs.GeneralEnum\n")
            .Append("--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.\n")
            .Append("--- @brief General Data key constants.\n\n");
        appendStubType(
            builder,
            "GeneralDataKey",
            "General Data table keys.",
            types.Select(type => new GeneralEnumMember(type.SourceKey, type.TypeName)));
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendStubType(builder, type.TypeName, type.SourceKey + " member keys.", type.Members);
        }
        builder.Append("\nreturn {\n")
            .Append("    GeneralDataKey = GeneralDataKey,\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append("    ")
                .Append(type.TypeName)
                .Append(" = ")
                .Append(type.TypeName)
                .Append(",\n");
        }
        builder.Append("}\n");
        return builder.ToString();
    }

    private static void appendRuntimeTable(
        StringBuilder builder,
        string tableName,
        IEnumerable<GeneralEnumMember> entries)
    {
        GeneralEnumMember[] values = entries.ToArray();
        if (values.Length == 0)
        {
            builder.Append("local ").Append(tableName).Append(" = {}\n");
            return;
        }
        builder.Append("local ").Append(tableName).Append(" = {\n");
        foreach (GeneralEnumMember entry in values)
        {
            builder.Append("    ")
                .Append(entry.Identifier)
                .Append(" = ")
                .Append(quote(entry.SourceKey))
                .Append(",\n");
        }
        builder.Append("}\n");
    }

    private static void appendStubType(
        StringBuilder builder,
        string typeName,
        string description,
        IEnumerable<GeneralEnumMember> entries)
    {
        builder.Append("--- @brief ").Append(description).Append("\n")
            .Append("---@class Source.Configs.GeneralEnum.").Append(typeName).Append("\n");
        foreach (GeneralEnumMember entry in entries)
            builder.Append("---@field ").Append(entry.Identifier).Append(" string\n");
        builder.Append("---@type Source.Configs.GeneralEnum.").Append(typeName).Append("\n")
            .Append("local ").Append(typeName).Append(" = {}\n");
    }

    private static string toTypeIdentifier(string value)
    {
        string[] parts = Regex.Split(value, "[^0-9A-Za-z]+")
            .Where(part => part.Length != 0)
            .ToArray();
        string result = string.Concat(parts.Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
        if (result.Length == 0)
            result = "GeneralData";
        if (char.IsDigit(result[0]))
            result = "GeneralData" + result;
        if (luaKeywords.Contains(result))
            result += "Data";
        return result;
    }

    private static string toMemberIdentifier(string value)
    {
        string result = Regex.Replace(value, "[^0-9A-Za-z_]", "_").Trim('_');
        if (result.Length == 0)
            result = "Key";
        if (char.IsDigit(result[0]))
            result = "_" + result;
        if (luaKeywords.Contains(result))
            result += "_";
        return result;
    }

    private static string uniqueIdentifier(string value, HashSet<string> usedNames)
    {
        string candidate = value;
        int suffix = 2;
        while (!usedNames.Add(candidate))
            candidate = value + "_" + suffix++;
        return candidate;
    }

    private static string quote(string value)
    {
        StringBuilder builder = new(value.Length + 2);
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (char.IsControl(character) && character <= byte.MaxValue)
                        builder.Append('\\').Append(((int)character).ToString("D3", CultureInfo.InvariantCulture));
                    else
                        builder.Append(character);
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private static bool contentEquals(string path, string expected)
    {
        return File.Exists(path)
            && string.Equals(File.ReadAllText(path, utf8), expected, StringComparison.Ordinal);
    }

    private void writePair(string runtimeText, string stubText)
    {
        string runtimeDirectory = Path.GetDirectoryName(RuntimePath)
            ?? throw new InvalidOperationException(RuntimePath);
        string stubDirectory = Path.GetDirectoryName(StubPath)
            ?? throw new InvalidOperationException(StubPath);
        Directory.CreateDirectory(runtimeDirectory);
        Directory.CreateDirectory(stubDirectory);
        byte[]? runtimeOriginal = File.Exists(RuntimePath) ? File.ReadAllBytes(RuntimePath) : null;
        byte[]? stubOriginal = File.Exists(StubPath) ? File.ReadAllBytes(StubPath) : null;
        string runtimeTemporary = createTemporaryPath(RuntimePath);
        string stubTemporary = createTemporaryPath(StubPath);
        try
        {
            writeDurable(runtimeTemporary, utf8.GetBytes(runtimeText));
            writeDurable(stubTemporary, utf8.GetBytes(stubText));
            File.Move(runtimeTemporary, RuntimePath, true);
            File.Move(stubTemporary, StubPath, true);
        }
        catch (Exception exception) when (isFileException(exception))
        {
            try
            {
                restore(RuntimePath, runtimeOriginal);
                restore(StubPath, stubOriginal);
            }
            catch (Exception rollbackException) when (isFileException(rollbackException))
            {
                throw new IOException(
                    exception.Message + "; rollback failed: " + rollbackException.Message,
                    exception);
            }
            throw;
        }
        finally
        {
            deleteTemporary(runtimeTemporary);
            deleteTemporary(stubTemporary);
        }
    }

    private static void restore(string path, byte[]? content)
    {
        if (content is null)
        {
            File.Delete(path);
            return;
        }
        string temporary = createTemporaryPath(path);
        try
        {
            writeDurable(temporary, content);
            File.Move(temporary, path, true);
        }
        finally
        {
            deleteTemporary(temporary);
        }
    }

    private static void writeDurable(string path, byte[] content)
    {
        using FileStream stream = new(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
        stream.Write(content);
        stream.Flush(true);
    }

    private static string createTemporaryPath(string path)
    {
        string directory = Path.GetDirectoryName(path) ?? throw new InvalidOperationException(path);
        return Path.Combine(directory, "." + Path.GetFileName(path) + "." + Guid.NewGuid().ToString("N") + ".tmp");
    }

    private static void deleteTemporary(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    private static bool isFileException(Exception exception)
    {
        return exception is IOException or UnauthorizedAccessException or SecurityException or DecoderFallbackException;
    }

    private sealed record GeneralEnumType(
        string SourceKey,
        string TypeName,
        IReadOnlyList<GeneralEnumMember> Members);

    private sealed record GeneralEnumMember(string SourceKey, string Identifier);
}
