from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

from ScriptTools.core_bindgen.metadata import lua_key, lua_string


GENERATED_MARKER = "-- AUTO-GENERATED by Ludork enum modules. DO NOT EDIT."
IDENTIFIER = re.compile(r"[A-Za-z_]\w*", re.ASCII)


def load_sfml_enums(path: Path) -> tuple[dict[str, dict[str, object]], dict[str, str]]:
    document = json.loads(path.read_text(encoding="utf-8"))
    enums: dict[str, dict[str, object]] = {}
    aliases: dict[str, str] = {}

    def visit(value: object) -> None:
        if isinstance(value, list):
            for item in value:
                visit(item)
        elif isinstance(value, dict):
            name = value.get("qualified_name")
            if isinstance(name, str):
                if value.get("kind") == "ENUM_DECL" and value.get("scoped"):
                    values = {
                        item["name"]: item["value"]
                        for item in value.get("children", [])
                        if item.get("kind") == "ENUM_CONSTANT_DECL"
                    }
                    if values and all(IDENTIFIER.fullmatch(part) for part in name.split("::")):
                        enums[name] = {"values": values, "valueType": name.replace("::", ".")}
                elif value.get("kind") == "TYPE_ALIAS_DECL":
                    canonical = value.get("type", {}).get("canonical")
                    if isinstance(canonical, str):
                        aliases[name] = canonical
            for item in value.values():
                visit(item)

    visit(document)
    return enums, aliases


def enum_module_paths(path: Path) -> dict[str, str]:
    enums, aliases = load_sfml_enums(path)
    result = {name: "Enums." + name.replace("::", ".") for name in enums}
    for name, canonical in aliases.items():
        visited: set[str] = set()
        while canonical in aliases and canonical not in visited:
            visited.add(canonical)
            canonical = aliases[canonical]
        if canonical in result:
            result[name] = result[canonical]
    return result


def scalar_type(value: object) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float) and math.isfinite(value):
        return "number"
    if isinstance(value, str):
        return "string"
    raise ValueError("enum values must be finite numbers, strings or booleans")


def scalar_literal(value: object) -> str:
    value_type = scalar_type(value)
    if value_type == "string":
        return lua_string(str(value))
    if value_type == "boolean":
        return "true" if value else "false"
    return str(value)


def generate_modules(scripts: Path, module: str, catalogue: dict[str, object]) -> None:
    if not IDENTIFIER.fullmatch(module):
        raise ValueError(f"invalid enum owner module: {module}")
    roots = [scripts / "Enums" / module, scripts / "stub" / "Enums" / module]
    outputs: dict[Path, str] = {}
    for name, record in sorted(catalogue.items()):
        parts = name.split(".")
        if not all(IDENTIFIER.fullmatch(part) for part in parts):
            raise ValueError(f"invalid enum member path: {name}")
        if not isinstance(record, dict) or not isinstance(record.get("values"), dict):
            raise ValueError(f"enum {name} must contain a values object")
        values = record["values"]
        if not values or any(not isinstance(key, str) or not key for key in values):
            raise ValueError(f"enum {name} must contain nonempty string keys")
        kinds = {scalar_type(value) for value in values.values()}
        if kinds <= {"integer", "number"}:
            inferred = "number" if "number" in kinds else "integer"
        elif len(kinds) == 1:
            inferred = next(iter(kinds))
        else:
            raise ValueError(f"enum {name} must contain one scalar value type")
        value_type = record.get("valueType", inferred)
        if not isinstance(value_type, str) or not all(IDENTIFIER.fullmatch(part) for part in value_type.split(".")):
            raise ValueError(f"invalid enum LuaLS value type: {name}")
        runtime = [GENERATED_MARKER, "return {"]
        runtime.extend(
            f"    {lua_key(key)} = {scalar_literal(float(value) if value_type == 'number' else value)},"
            for key, value in sorted(values.items())
        )
        runtime.extend(["}", ""])
        enum_type = f"Enums.{module}.{name}"
        stub = [GENERATED_MARKER, f"---@meta {enum_type}", "", f"---@class {enum_type}"]
        stub.extend(f"---@field {lua_key(key)} {value_type}" for key in sorted(values))
        stub.extend([f"---@type {enum_type}", "local enum = {}", "", "return enum", ""])
        relative = Path(*parts)
        outputs[(roots[0] / relative).with_suffix(".lua")] = "\n".join(runtime)
        outputs[(roots[1] / relative).with_suffix(".d.lua")] = "\n".join(stub)

    stale: list[Path] = []
    for root in roots:
        for path in root.rglob("*.lua"):
            if path not in outputs and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                stale.append(path)
    for path in outputs:
        if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            raise ValueError(f"refusing to overwrite handwritten enum module: {path}")
    for root in roots:
        root.mkdir(parents=True, exist_ok=True)
    for path, contents in outputs.items():
        if path.exists():
            current = path.read_text(encoding="utf-8")
            if current == contents:
                continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
    for path in stale:
        path.unlink()
    for root in roots:
        if root.exists():
            for directory in sorted((path for path in root.rglob("*") if path.is_dir()), reverse=True):
                if not any(directory.iterdir()):
                    directory.rmdir()


def check_native_modules(scripts: Path, module: str, names: list[str]) -> None:
    missing: list[Path] = []
    for name in names:
        relative = Path(*name.split("."))
        for prefix, suffix in (("Enums", ".lua"), ("stub/Enums", ".d.lua")):
            path = (scripts / prefix / module / relative).with_suffix(suffix)
            if not path.is_file() or not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                missing.append(path)
    if missing:
        paths = "\n".join(f"  {path}" for path in missing)
        raise ValueError(
            "Native enum modules are missing. Run a desktop native build before "
            f"cross-compiling or using static Lua modules:\n{paths}"
        )


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate pure Lua enum modules and their declarations")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--catalogue", type=Path)
    source.add_argument("--sfml-api", type=Path)
    parser.add_argument("--module", required=True)
    parser.add_argument("--scripts-directory", type=Path, required=True)
    options = parser.parse_args(arguments)
    if options.sfml_api is not None:
        enums, _ = load_sfml_enums(options.sfml_api)
        prefix = options.module + "::"
        catalogue = {name.removeprefix(prefix).replace("::", "."): record for name, record in enums.items() if name.startswith(prefix)}
    else:
        catalogue = json.loads(options.catalogue.read_text(encoding="utf-8"))
        if not isinstance(catalogue, dict):
            raise ValueError("enum catalogue must be an object")
    generate_modules(options.scripts_directory, options.module, catalogue)
    return 0
