ASSET_GROUP = "Assets"
DATA_GROUP = "Data"
SCRIPT_GROUP = "Scripts"
RESOURCE_GROUPS = (ASSET_GROUP, DATA_GROUP, SCRIPT_GROUP)
PACKAGE_EXTENSION = ".ldpak"
RESOURCE_PACKAGES = tuple(f"{name}{PACKAGE_EXTENSION}" for name in RESOURCE_GROUPS)
ASSET_PATH_PREFIX = f"/Game/{ASSET_GROUP}/"
DATA_PATH_PREFIX = f"{DATA_GROUP}/"
SCRIPT_PATH_PREFIX = f"{SCRIPT_GROUP}/"
LUA_SOURCE_EXTENSION = ".lua"
LUA_COMPILED_EXTENSION = ".luac"
SCRIPT_ENTRY_PATHS = tuple(f"Entry{extension}" for extension in (LUA_SOURCE_EXTENSION, LUA_COMPILED_EXTENSION))
DATA_EXTENSION = ".json"
ENCRYPTED_DATA_EXTENSION = ".ldc"
ANIMATION_CACHE_SUFFIX = f".anim{DATA_EXTENSION}"
ENCRYPTED_ANIMATION_CACHE_SUFFIX = f".anim{ENCRYPTED_DATA_EXTENSION}"
SHADER_EXTENSIONS = {
    ".frag": ".fragc",
    ".vert": ".vertc",
    ".geom": ".geomc",
}
