from __future__ import annotations

import argparse
import json
import pathlib
import re
import struct

from . import resource_constants as resources
from . import runtime_formats as formats


def _header(namespace: str, declarations: list[str]) -> str:
    return "\n".join((
        "// Generated by ScriptTools runtime-constants. Do not edit.",
        "#pragma once", "", "#include <array>", "#include <cstddef>",
        "#include <cstdint>", "#include <string_view>", "",
        f"namespace ludork::generated::{namespace} {{", "",
        *declarations, "", f"}}  // namespace ludork::generated::{namespace}", "",
    ))


def _integer(kind: str, name: str, value: int) -> str:
    return f"inline constexpr {kind} {name} = {value}{'ULL' if kind == 'std::uint64_t' else ''};"


def _magic(name: str, value: bytes) -> str:
    return f"inline constexpr std::array<std::uint8_t, {len(value)}> {name} = {{{', '.join(str(byte) for byte in value)}}};"


def _layout(name: str, fields: tuple[tuple[str, str], ...]) -> list[str]:
    declarations = []
    codes = "<"
    for field, code in fields:
        declarations.append(_integer("std::size_t", f"{name}{field}Offset", struct.calcsize(codes)))
        codes += code
    declarations.append(_integer("std::size_t", f"{name}Size", struct.calcsize(codes)))
    return declarations


def _lighting_limit(project: pathlib.Path) -> int:
    path = project / "Assets/Shaders/Global/UnoccludedLightPass.frag"
    source = path.read_text(encoding="utf-8")
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", source, flags=re.DOTALL)
    declarations = re.findall(r"^[ \t]*#[ \t]*define[ \t]+LUDORK_MAX_SHADER_LIGHTS\b([^\n]*)", source, re.MULTILINE)
    if len(declarations) != 1 or re.fullmatch(r"[ \t]+[1-9][0-9]*[ \t]*", declarations[0]) is None:
        raise ValueError(f"Expected one integer LUDORK_MAX_SHADER_LIGHTS definition in {path}")
    value = int(declarations[0])
    if not 1 <= value <= 256:
        raise ValueError(f"LUDORK_MAX_SHADER_LIGHTS must be within 1..256: {value}")
    return value


def generate(project: pathlib.Path, output: pathlib.Path) -> None:
    lighting_limit = _lighting_limit(project)
    archive = [
        _magic("Magic", formats.LDPK_MAGIC),
        _integer("std::uint16_t", "Version", formats.LDPK_VERSION),
        _integer("std::uint16_t", "Flags", formats.LDPK_FLAGS),
        _integer("std::uint32_t", "DirectoryFlag", formats.LDPK_DIRECTORY_FLAG),
        _integer("std::uint64_t", "Alignment", formats.LDPK_ALIGNMENT),
        *_layout("Header", formats.LDPK_HEADER_FIELDS),
        *_layout("Entry", formats.LDPK_ENTRY_FIELDS),
    ]
    encrypted = [
        _magic("ShaderMagic", formats.SHADER_MAGIC),
        _magic("DataMagic", formats.DATA_MAGIC),
        _integer("std::uint8_t", "Version", formats.ENCRYPTED_VERSION),
        _integer("std::uint8_t", "ZlibFlag", formats.ENCRYPTED_ZLIB_FLAG),
        _integer("std::uint64_t", "KeySeed", formats.KEY_SEED),
        _integer("std::uint64_t", "StreamMultiplier", formats.STREAM_MULTIPLIER),
        _integer("std::uint64_t", "StreamFallback", formats.STREAM_FALLBACK),
        _integer("unsigned int", "StreamRightShiftFirst", formats.STREAM_RIGHT_SHIFT_FIRST),
        _integer("unsigned int", "StreamLeftShift", formats.STREAM_LEFT_SHIFT),
        _integer("unsigned int", "StreamRightShiftLast", formats.STREAM_RIGHT_SHIFT_LAST),
        _integer("std::size_t", "StreamBlockSize", formats.STREAM_BLOCK_SIZE),
        _integer("std::uint32_t", "MaximumShaderSize", formats.MAX_SHADER_SIZE),
        _integer("std::uint32_t", "MaximumDataSize", formats.MAX_DATA_SIZE),
        *_layout("Header", formats.ENCRYPTED_HEADER_FIELDS),
    ]
    names = {
        "AssetGroup": resources.ASSET_GROUP,
        "DataGroup": resources.DATA_GROUP,
        "ScriptGroup": resources.SCRIPT_GROUP,
        "PackageExtension": resources.PACKAGE_EXTENSION,
        "AssetPathPrefix": resources.ASSET_PATH_PREFIX,
        "DataPathPrefix": resources.DATA_PATH_PREFIX,
        "ScriptPathPrefix": resources.SCRIPT_PATH_PREFIX,
        "LuaSourceExtension": resources.LUA_SOURCE_EXTENSION,
        "LuaCompiledExtension": resources.LUA_COMPILED_EXTENSION,
        "ScriptEntrySource": resources.SCRIPT_ENTRY_PATHS[0],
        "ScriptEntryCompiled": resources.SCRIPT_ENTRY_PATHS[1],
        "DataExtension": resources.DATA_EXTENSION,
        "EncryptedDataExtension": resources.ENCRYPTED_DATA_EXTENSION,
        "AnimationCacheSuffix": resources.ANIMATION_CACHE_SUFFIX,
        "EncryptedAnimationCacheSuffix": resources.ENCRYPTED_ANIMATION_CACHE_SUFFIX,
    }
    resource_values = [f"inline constexpr char {name}[] = {json.dumps(value)};" for name, value in names.items()]
    resource_values.extend((
        "struct ShaderExtension { std::string_view source; std::string_view encrypted; };",
        f"inline constexpr std::array<ShaderExtension, {len(resources.SHADER_EXTENSIONS)}> ShaderExtensions = {{{{",
        *(f"    {{{json.dumps(source)}, {json.dumps(encrypted)}}}," for source, encrypted in resources.SHADER_EXTENSIONS.items()),
        "}};",
    ))
    files = {
        "LdPakFormatConstants.hpp": _header("ldpak", archive),
        "EncryptedPayloadConstants.hpp": _header("encrypted", encrypted),
        "ResourceFileConstants.hpp": _header("resources", resource_values),
        "LightingConstants.hpp": _header("lighting", [_integer("int", "MaximumShaderLights", lighting_limit)]),
    }
    directory = output / "LudorkGenerated"
    directory.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        path = directory / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ScriptTools runtime-constants")
    parser.add_argument("language", choices=("cpp",))
    parser.add_argument("project_root", type=pathlib.Path)
    parser.add_argument("output_directory", type=pathlib.Path)
    parsed = parser.parse_args(arguments)
    try:
        generate(parsed.project_root.resolve(), parsed.output_directory.resolve())
    except (OSError, ValueError) as exception:
        parser.exit(1, f"{exception}\n")
    return 0
