from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
from urllib.parse import quote, unquote, urlsplit, urlunsplit


def load(configuration: str) -> dict[str, object]:
    settings: dict[str, object] = {"enabled": False}
    filename = os.environ.get("LUDORK_SERVER_CONFIG_FILE", "")
    if configuration == "Debug" and filename:
        path = pathlib.Path(filename).expanduser()
        if path.is_file():
            try:
                settings = json.loads(path.read_text(encoding="utf-8-sig"))
            except (OSError, ValueError) as error:
                raise ValueError("Cannot read the test server configuration.") from error
            if not isinstance(settings, dict) or not isinstance(settings.get("enabled"), bool):
                raise ValueError("The test server configuration requires a boolean enabled field.")
    else:
        enabled = os.environ.get("LUDORK_SERVER_ENABLED", "0")
        if enabled not in ("", "0", "1"):
            raise ValueError("LUDORK_SERVER_ENABLED must be 0 or 1.")
        if enabled == "1":
            settings = {"enabled": True, "url": os.environ.get("LUDORK_SERVER_URL", ""),
                        "key": os.environ.get("LUDORK_SERVER_KEY", "")}
    if settings.get("enabled") is not True:
        return {"enabled": False, "url": "", "key": ""}
    url, key = settings.get("url"), settings.get("key")
    if not isinstance(url, str) or not isinstance(key, str):
        raise ValueError("An enabled Ludork server requires a URL and key.")
    try:
        parsed = urlsplit(url)
        project = unquote(parsed.path.strip("/"), errors="strict")
        valid = (parsed.scheme == "http" and parsed.hostname and parsed.port != 0
                 and parsed.username is None and parsed.password is None
                 and not parsed.query and not parsed.fragment
                 and len(parsed.path.strip("/").split("/")) == 1
                 and project not in ("", ".", "..") and "/" not in project and "\\" not in project
                 and len(project.encode("utf-8")) <= 64
                 and not any(ord(char) < 32 or ord(char) == 127 for char in project)
                 and not any(ord(char) <= 32 or ord(char) == 127 for char in url))
    except (ValueError, UnicodeError):
        valid = False
    if not valid:
        raise ValueError("The Ludork server URL must be http://host[:port]/project without credentials, a query or fragment.")
    if not key or len(key) > 4096 or any(not 33 <= ord(char) <= 126 for char in key):
        raise ValueError("The Ludork server key must contain 1 to 4096 visible ASCII characters without spaces.")
    normalized = urlunsplit(("http", parsed.netloc, "/" + quote(project, safe=""), "", ""))
    return {"enabled": True, "url": normalized, "key": key}


def fingerprint(configuration: str) -> str:
    value = json.dumps(load(configuration), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def generate(directory: pathlib.Path, configuration: str) -> None:
    settings = load(configuration)
    lines = ["// Generated by ScriptTools server-config. Do not edit.", "#pragma once", ""]
    if settings["enabled"]:
        lines.extend(["#define LUDORK_SERVER_AVAILABLE 1", ""])
    lines.append("namespace ludork::generated::server {")
    for field in ("url", "key"):
        encoded = "".join(f"\\{value:03o}" for value in str(settings[field]).encode("utf-8"))
        lines.append(f'inline constexpr char {field.title()}[] = "{encoded}";')
    lines.extend(["}", ""])
    path = directory / "LudorkGenerated" / "ServerConfig.hpp"
    content = "\n".join(lines)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8", newline="\n")


def cleanup(project: pathlib.Path) -> None:
    intermediate = project.resolve() / "Intermediate"
    if intermediate.is_dir():
        for path in intermediate.glob("*/ServerConfig/Release/LudorkGenerated/ServerConfig.hpp"):
            if path.is_file() and not path.is_symlink() and path.resolve().is_relative_to(intermediate):
                path.unlink()


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ScriptTools server-config")
    commands = parser.add_subparsers(dest="operation", required=True)
    generator = commands.add_parser("generate")
    generator.add_argument("directory", type=pathlib.Path)
    generator.add_argument("configuration", choices=("Debug", "Release", "RelWithDebInfo", "MinSizeRel"))
    cleaner = commands.add_parser("cleanup")
    cleaner.add_argument("project", type=pathlib.Path)
    args = parser.parse_args(arguments)
    try:
        if args.operation == "generate":
            generate(args.directory, args.configuration)
        else:
            cleanup(args.project)
    except (OSError, ValueError) as error:
        parser.exit(1, f"{error}\n")
    return 0
