from __future__ import annotations

import hashlib
import os
import pathlib
import re
import shutil
import tempfile

from ScriptTools.lua_syntax.constants import LUA_RESERVED_WORDS

from .ui_assets import (
    ASSETS_RELATIVE_PATH,
    _asset_key_from_path,
    _is_link,
    _load_json,
    _reference_nodes,
    validate_assets,
)
from .ui_property_values import UiAssetError
from .ui_window_generation import OUTPUT_ROOT as WINDOW_OUTPUT_ROOT, window_outputs


GENERATED_MARKER = "-- Generated by ScriptTools ui-assets generate. Do not edit."
OUTPUT_ROOTS = (
    pathlib.Path("Scripts/Source/UI"),
    pathlib.Path("Scripts/stub/Source/UI"),
    WINDOW_OUTPUT_ROOT,
)
_TYPE_ESCAPE = "__ui_"


def _lua_string(value: str) -> str:
    escaped: list[str] = []
    for character in value:
        if character in {'"', "\\"} or ord(character) < 32 or ord(character) == 127:
            escaped.append(f"\\{ord(character):03d}")
        else:
            escaped.append(character)
    return '"' + "".join(escaped) + '"'


def _identifier(value: str) -> bool:
    return re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", value) is not None and value not in LUA_RESERVED_WORDS


def _type_key(asset_key: str) -> str:
    return ".".join(
        part
        if _identifier(part) and not part.startswith(_TYPE_ESCAPE)
        else _TYPE_ESCAPE + part.encode("utf-8").hex()
        for part in asset_key.split("/")
    )


def _field_name(name: str) -> str:
    return name if _identifier(name) else f"[{_lua_string(name)}]"


def _root_type(asset_key: str, assets: dict[str, dict[str, object]]) -> str:
    control_id = str(assets[asset_key]["root"]["controlId"])
    if control_id.startswith("Project:"):
        return _root_type(control_id.removeprefix("Project:"), assets)
    return control_id


def _map_lines(name: str, entries: list[tuple[str, str]], record: str) -> list[str]:
    if len(entries) == 1:
        node_name, expression = entries[0]
        lines = [
            f"    local {name} = {{ {_field_name(node_name)} = {expression} }}"
        ]
    elif entries:
        lines = [f"    local {name} = {{"]
        for index, (node_name, expression) in enumerate(entries):
            comma = "," if index + 1 < len(entries) else ""
            lines.append(
                f"        {_field_name(node_name)} = {expression}{comma}"
            )
        lines.append("    }")
    else:
        lines = [f"    local {name} = {{}}"]
    lines.extend([f"    ---@cast {name} {record}", f"    self.{name} = {name}"])
    return lines


def _field_lines(fields: list[tuple[str, str]]) -> list[str]:
    width = max((len(name) for name, _ in fields), default=0)
    return [f"---@field {name.ljust(width)} {type_name}" for name, type_name in fields]


def _render(asset_key: str, assets: dict[str, dict[str, object]]) -> tuple[str, str]:
    value = assets[asset_key]
    type_key = _type_key(asset_key)
    view_type = "Source.UI." + type_key
    controls_type = "Source.UIBase.GeneratedControls." + type_key
    assets_type = "Source.UIBase.GeneratedAssets." + type_key
    module = "Source.UI." + asset_key.replace("/", ".")
    meta = module if all(_identifier(part) for part in module.split(".")) else _lua_string(module)
    controls: list[tuple[str, str]] = []
    nested_assets: list[tuple[str, str]] = []
    for node in sorted(_reference_nodes(value["root"]), key=lambda node: node["name"]):
        if str(node["controlId"]).startswith("Project:"):
            nested_assets.append((str(node["name"]), str(node["controlId"]).removeprefix("Project:")))
        else:
            controls.append((str(node["name"]), str(node["controlId"])))
    child_modules = {
        key: f"ChildView{index}"
        for index, key in enumerate(sorted({key for _, key in nested_assets}), start=1)
    }
    control_values = [
        (name, f"assert(self.instance:requireControl({_lua_string(name)}))")
        for name, _ in controls
    ]
    asset_values = [
        (name, f"self:own({child_modules[key]}.new(assert(self.instance:requireAsset({_lua_string(name)}))))")
        for name, key in nested_assets
    ]
    design_size = value["designSize"]
    runtime = [
        GENERATED_MARKER,
        'local UiView = require("Source.UIBase.UiView")',
        *[
            f"local {alias} = require({_lua_string('Source.UI.' + key.replace('/', '.'))})"
            for key, alias in child_modules.items()
        ],
        "",
        f"---@class {view_type}",
        "local View = {}",
        "",
        f"View.assetKey = {_lua_string(asset_key)}",
        f"View.designSize = sf.Vector2f.new({design_size['width']}, {design_size['height']})",
        "",
        "function View:init(instance)",
        "    UiView.init(self, instance)",
        *_map_lines("controls", control_values, controls_type),
        *_map_lines("assets", asset_values, assets_type),
        "end",
        "",
        "return class(View, UiView)",
        "",
    ]
    stub = [
        GENERATED_MARKER,
        "---@meta " + meta,
        "",
        f"---@class {controls_type}",
        *_field_lines([(_field_name(name), type_name) for name, type_name in controls]),
        "",
        f"---@class {assets_type}",
        *_field_lines([(_field_name(name), "Source.UI." + _type_key(key)) for name, key in nested_assets]),
        "",
        f"---@class {view_type}: Source.UIBase.UiView",
        *_field_lines([
            ("root", _root_type(asset_key, assets)),
            ("controls", controls_type),
            ("assets", assets_type),
            ("new", f"fun(instance?: Engine.AssetInstance): {view_type}"),
        ]),
        "local View = {}",
        "",
        "---@param instance Engine.AssetInstance | nil",
        "function View:init(instance) end",
        "",
        "return View",
        "",
    ]
    return "\n".join(runtime), "\n".join(stub)


def _check_path(root: pathlib.Path, relative: pathlib.Path) -> None:
    current = root
    for index, part in enumerate(relative.parts):
        current /= part
        if _is_link(current):
            raise UiAssetError(f"UI generation does not follow links: {current}")
        if current.exists() and index + 1 < len(relative.parts) and not current.is_dir():
            raise UiAssetError(f"UI generation directory is occupied by a file: {current}")


def _generated(data: bytes) -> bool:
    return data.splitlines()[:1] == [GENERATED_MARKER.encode("utf-8")]


def _exact_case_path(root: pathlib.Path, relative: pathlib.Path) -> bool:
    current = root
    for part in relative.parts:
        if not current.is_dir():
            return False
        child = next((path for path in current.iterdir() if path.name == part), None)
        if child is None:
            return False
        current = child
    return True


def _output_changes(root: pathlib.Path, outputs: dict[pathlib.Path, bytes]) -> dict[pathlib.Path, bytes | None]:
    changes: dict[pathlib.Path, bytes | None] = {}
    spellings: dict[str, pathlib.Path] = {}
    for relative, data in outputs.items():
        for path in (relative, *relative.parents):
            folded = path.as_posix().casefold()
            if folded in spellings and spellings[folded] != path:
                raise UiAssetError(
                    f"UI output paths conflict on case-insensitive filesystems: {spellings[folded]}, {path}"
                )
            spellings[folded] = path
        _check_path(root, relative)
        target = root / relative
        if target.exists():
            if not target.is_file():
                raise UiAssetError(f"UI generated file is occupied by a directory: {target}")
            existing = target.read_bytes()
            if not _generated(existing):
                raise UiAssetError(f"UI generated file conflicts with handwritten content: {target}")
            if existing == data and _exact_case_path(root, relative):
                continue
        changes[relative] = data
    for relative_root in OUTPUT_ROOTS:
        _check_path(root, relative_root)
        output_root = root / relative_root
        if not output_root.exists():
            continue
        if not output_root.is_dir():
            raise UiAssetError(f"UI generation directory is occupied by a file: {output_root}")
        for path in sorted(output_root.rglob("*")):
            relative = path.relative_to(root)
            if _is_link(path):
                raise UiAssetError(f"UI generation does not follow links: {path}")
            if relative in outputs or not path.is_file() or path.suffix != ".lua":
                continue
            if _generated(path.read_bytes()):
                changes[relative] = None
    return dict(sorted(changes.items()))


def _case_directory_moves(root: pathlib.Path, outputs: dict[pathlib.Path, bytes]) -> list[tuple[pathlib.Path, pathlib.Path]]:
    moves: list[tuple[pathlib.Path, pathlib.Path]] = []
    parents = {parent for path in outputs for parent in path.parents if parent not in OUTPUT_ROOTS}
    for relative in sorted(parents, key=lambda path: (len(path.parts), path.as_posix())):
        if not any(output_root in relative.parents for output_root in OUTPUT_ROOTS):
            continue
        target = root / relative
        if not target.is_dir():
            continue
        exact = next((path for path in target.parent.iterdir() if path.name == target.name), None)
        if exact is not None:
            continue
        original = next(path for path in target.parent.iterdir() if path.samefile(target))
        for path in original.rglob("*"):
            if path.is_file() and not _generated(path.read_bytes()):
                raise UiAssetError(f"UI directory case change conflicts with handwritten content: {path}")
        moves.append((original, target))
    return moves


def _install(
    root: pathlib.Path,
    changes: dict[pathlib.Path, bytes | None],
    directory_moves: list[tuple[pathlib.Path, pathlib.Path]],
) -> None:
    created_directories: list[pathlib.Path] = []
    moved_directories: list[tuple[pathlib.Path, pathlib.Path]] = []
    installed: list[pathlib.Path] = []
    backups: dict[pathlib.Path, pathlib.Path] = {}
    with tempfile.TemporaryDirectory(prefix=".ludork-ui-", dir=root) as staging_name:
        staging = pathlib.Path(staging_name)
        prepared: dict[pathlib.Path, pathlib.Path] = {}
        for index, (relative, data) in enumerate(changes.items()):
            target = root / relative
            if target.exists():
                backup = staging / f"{index}.backup"
                shutil.copy2(target, backup)
                backups[relative] = backup
            if data is not None:
                output = staging / f"{index}.new"
                output.write_bytes(data)
                if target.exists():
                    os.chmod(output, target.stat().st_mode)
                prepared[relative] = output
        try:
            for original, target in directory_moves:
                original.rename(target)
                moved_directories.append((original, target))
            for relative, data in sorted(changes.items(), key=lambda item: (item[1] is not None, item[0])):
                target = root / relative
                if data is None:
                    target.unlink()
                else:
                    missing: list[pathlib.Path] = []
                    parent = target.parent
                    while not parent.exists():
                        missing.append(parent)
                        parent = parent.parent
                    for directory in reversed(missing):
                        directory.mkdir()
                        created_directories.append(directory)
                    os.replace(prepared[relative], target)
                installed.append(relative)
        except OSError as exception:
            failures: list[str] = []
            for relative in reversed(installed):
                try:
                    if relative in backups:
                        os.replace(backups[relative], root / relative)
                    else:
                        (root / relative).unlink(missing_ok=True)
                except OSError as rollback_error:
                    failures.append(f"{relative}: {rollback_error}")
            for directory in reversed(created_directories):
                try:
                    directory.rmdir()
                except OSError as rollback_error:
                    failures.append(f"{directory}: {rollback_error}")
            for original, target in reversed(moved_directories):
                try:
                    target.rename(original)
                except OSError as rollback_error:
                    failures.append(f"{target}: {rollback_error}")
            if failures:
                raise UiAssetError(
                    f"UI generation failed ({exception}); rollback also failed: {'; '.join(failures)}"
                ) from exception
            raise UiAssetError(f"UI generation failed; prior files restored: {exception}") from exception


def _prepare_generation(project_root: pathlib.Path) -> tuple[pathlib.Path, dict[pathlib.Path, bytes], dict[pathlib.Path, bytes | None]]:
    root = project_root.expanduser().resolve()
    if not root.is_dir():
        raise UiAssetError(f"UI project directory does not exist: {root}")
    try:
        _check_path(root, ASSETS_RELATIVE_PATH)
        assets_root = root / ASSETS_RELATIVE_PATH
        if assets_root.exists() and not assets_root.is_dir():
            raise UiAssetError(f"UI asset directory is occupied by a file: {assets_root}")
        for path in assets_root.rglob("*"):
            if _is_link(path):
                raise UiAssetError(f"UI generation does not follow links: {path}")
        validate_assets(root, structure_only=True)
        assets: dict[str, dict[str, object]] = {}
        inputs: dict[pathlib.Path, bytes | None] = {}
        case_keys: dict[str, str] = {}
        for path in sorted(assets_root.rglob("*.json")):
            _check_path(root, path.relative_to(root))
            if not path.is_file():
                continue
            asset_key = _asset_key_from_path(path, assets_root)
            if any("." in part for part in asset_key.split("/")):
                raise UiAssetError(f"UI asset paths cannot contain dots in Lua module segments: {asset_key}")
            folded = asset_key.casefold()
            if folded in case_keys:
                raise UiAssetError(f"UI assets conflict on case-insensitive filesystems: {case_keys[folded]}, {asset_key}")
            case_keys[folded] = asset_key
            assets[asset_key] = _load_json(path)
            inputs[path.relative_to(root)] = path.read_bytes()
        outputs: dict[pathlib.Path, bytes] = {}
        for asset_key in assets:
            runtime, stub = _render(asset_key, assets)
            asset_path = pathlib.Path(*asset_key.split("/"))
            outputs[OUTPUT_ROOTS[0] / asset_path.with_suffix(".lua")] = runtime.encode("utf-8")
            outputs[OUTPUT_ROOTS[1] / asset_path.with_suffix(".d.lua")] = stub.encode("utf-8")
        outputs.update(window_outputs(root, {
            "Source.UI." + key.replace("/", "."): "Source.UI." + _type_key(key)
            for key in assets
        }, GENERATED_MARKER, inputs))
        return root, outputs, inputs
    except OSError as exception:
        raise UiAssetError(f"UI generation could not access project files: {exception}") from exception


def generation_manifest(project_root: pathlib.Path) -> dict[str, object]:
    root, outputs, inputs = _prepare_generation(project_root)
    output_paths = set(outputs)
    for relative_root in OUTPUT_ROOTS:
        _check_path(root, relative_root)
        for path in (root / relative_root).rglob("*"):
            if _is_link(path):
                raise UiAssetError(f"UI generation does not follow links: {path}")
            if path.is_file():
                output_paths.add(path.relative_to(root))
    return {
        "inputs": {
            path.as_posix(): hashlib.sha256(data).hexdigest() if data is not None else "missing"
            for path, data in sorted(inputs.items())
        },
        "outputPaths": [path.as_posix() for path in sorted(output_paths)],
    }


def generate_assets(project_root: pathlib.Path, *, check: bool = False) -> list[str]:
    root, outputs, _ = _prepare_generation(project_root)
    try:
        changes = _output_changes(root, outputs)
        directory_moves = _case_directory_moves(root, outputs)
        if changes and not check:
            _install(root, changes, directory_moves)
        return [path.as_posix() for path in changes]
    except OSError as exception:
        raise UiAssetError(f"UI generation could not access project files: {exception}") from exception
