using Ludork.Models;
using Ludork.Plugin.Abstractions;
using MoonSharp.Interpreter;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json.Nodes;

namespace Ludork.Services;

public sealed class GameVariableService : IGameVariableCatalog
{
    public const string GeneratedMarker = "-- AUTO-GENERATED by Ludork Game Variable Manager. DO NOT EDIT.";

    private const string RuntimeRelativePath = "Scripts/Source/Configs/GameVariables.lua";
    private const string MetadataRelativePath = "Scripts/Source/Configs/GameVariables_meta.lua";
    private static readonly UTF8Encoding utf8 = new(false, true);
    private readonly LuaMetadataService metadataService;
    private readonly EditorDocumentRegistry documents;
    private readonly List<GameVariableDefinition> variables = [];
    private readonly Dictionary<string, int> variableIndices = new(StringComparer.Ordinal);
    private bool committing;
    private readonly ReadOnlyCollection<GameVariableDefinition> readonlyVariables;

    public GameVariableService(
        string projectPath,
        LuaMetadataService metadataService,
        EditorDocumentRegistry documents)
    {
        if (!Path.IsPathFullyQualified(projectPath))
            throw new ArgumentException(nameof(projectPath));
        ArgumentNullException.ThrowIfNull(metadataService);
        ArgumentNullException.ThrowIfNull(documents);
        string normalizedProjectPath = Path.TrimEndingDirectorySeparator(Path.GetFullPath(projectPath));
        if (!string.Equals(
            normalizedProjectPath,
            Path.TrimEndingDirectorySeparator(Path.GetFullPath(metadataService.ProjectPath)),
            StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(nameof(metadataService));
        }

        this.metadataService = metadataService;
        this.documents = documents;
        readonlyVariables = variables.AsReadOnly();
        RuntimePath = Path.Combine(normalizedProjectPath, RuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        MetadataPath = Path.Combine(normalizedProjectPath, MetadataRelativePath.Replace('/', Path.DirectorySeparatorChar));

        EditorDocument? existing = documents.FindByPath(RuntimePath);
        if (existing is null)
        {
            bool runtimeExists = File.Exists(RuntimePath);
            bool metadataExists = File.Exists(MetadataPath);
            if (runtimeExists != metadataExists)
                throw new InvalidDataException("The generated game variable file pair is incomplete");
            if (runtimeExists)
                variables.AddRange(loadExisting().OrderBy(value => value.Name, StringComparer.Ordinal));
            Document = documents.Register(
                "GameVariables",
                "GameVariables",
                RuntimePath,
                serializeVariables(),
                isNew: !runtimeExists);
        }
        else
        {
            Document = existing;
            readDocument();
        }
        documents.BindPath(Document, MetadataPath);
        rebuildIndices();
        Document.SaveAdapter = prepareSaveOutputs;
        Document.Changed += onDocumentChanged;
    }

    public string RuntimePath { get; }
    public string MetadataPath { get; }
    public EditorDocument Document { get; }
    public IReadOnlyList<GameVariableDefinition> Variables => readonlyVariables;
    public long Revision => Document.Revision;
    public bool IsModified => Document.IsModified;
    public event EventHandler? Changed;
    public event EventHandler? Saved;

    public static bool IsValidName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)
            || !string.Equals(name, name.Trim(), StringComparison.Ordinal)
            || string.Equals(name, "attrs", StringComparison.Ordinal))
        {
            return false;
        }
        return !name.Any(char.IsControl);
    }

    public bool TryGet(string name, out GameVariableDefinition? definition)
    {
        definition = variableIndices.TryGetValue(name, out int index) ? variables[index] : null;
        return definition is not null;
    }

    public long BeginHistoryGesture() => documents.CreateGestureId();

    public HistoryResult Undo() => documents.Undo(Document);

    public HistoryResult Redo() => documents.Redo(Document);

    public GameVariableSaveResult Create(string name, GameVariableType type)
    {
        if (!IsValidName(name))
            return GameVariableSaveResult.Failed("Game variable name is invalid");
        if (!Enum.IsDefined(type))
            return GameVariableSaveResult.Failed("Game variable type is invalid");
        if (variableIndices.ContainsKey(name))
            return GameVariableSaveResult.Failed($"Game variable {name} already exists");
        documents.Capture(Document, "Create game variable");
        variables.Add(new GameVariableDefinition(name, type, createDefault(type)));
        variables.Sort((left, right) => StringComparer.Ordinal.Compare(left.Name, right.Name));
        return commitMutation();
    }

    public GameVariableSaveResult Delete(string name)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        documents.Capture(Document, "Delete game variable");
        variables.RemoveAt(index);
        return commitMutation();
    }

    public GameVariableSaveResult ChangeType(string name, GameVariableType type)
    {
        if (!Enum.IsDefined(type))
            return GameVariableSaveResult.Failed("Game variable type is invalid");
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        GameVariableDefinition current = variables[index];
        if (current.Type == type)
            return GameVariableSaveResult.Completed(string.Empty);
        documents.Capture(Document, "Change game variable type");
        variables[index] = new GameVariableDefinition(
            current.Name,
            type,
            createDefault(type),
            current.Remark);
        return commitMutation(index);
    }

    public GameVariableSaveResult SetInitialValue(string name, JsonNode? initialValue, long gestureId = 0)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        GameVariableDefinition current = variables[index];
        try
        {
            GameVariableLuaCodec.ValidateInitialValue(current.Type, initialValue);
        }
        catch (InvalidDataException exception)
        {
            return GameVariableSaveResult.Failed(exception.Message);
        }
        if (JsonNode.DeepEquals(current.InitialValue, initialValue))
            return GameVariableSaveResult.Completed(string.Empty);
        documents.Capture(Document, "Edit game variable initial value", gestureId: gestureId);
        variables[index] = new GameVariableDefinition(
            current.Name,
            current.Type,
            initialValue,
            current.Remark);
        return commitMutation(index);
    }

    public GameVariableSaveResult SetRemark(string name, string? remark, long gestureId = 0)
    {
        int index = findIndex(name);
        if (index < 0)
            return GameVariableSaveResult.Failed($"Game variable {name} does not exist");
        string normalized = remark ?? string.Empty;
        GameVariableDefinition current = variables[index];
        if (string.Equals(current.Remark, normalized, StringComparison.Ordinal))
            return GameVariableSaveResult.Completed(string.Empty);
        documents.Capture(Document, "Edit game variable remark", gestureId: gestureId);
        variables[index] = new GameVariableDefinition(
            current.Name,
            current.Type,
            current.InitialValue,
            normalized);
        return commitMutation(index);
    }

    internal Func<GameVariableSaveResult>? CapturePendingSave()
    {
        if (!IsModified)
            return null;
        GameVariableDefinition[] captured = variables.ToArray();
        return () =>
        {
            try
            {
                IReadOnlyDictionary<string, byte[]> outputs = prepareSaveOutputs(captured);
                writePair(outputs[RuntimePath], outputs[MetadataPath]);
                return GameVariableSaveResult.Completed(
                    RuntimeRelativePath + Environment.NewLine + MetadataRelativePath);
            }
            catch (Exception exception) when (isSaveException(exception))
            {
                return GameVariableSaveResult.Failed(formatFailure(exception));
            }
        };
    }

    internal void CompletePendingSave(EditorDocumentState savedState)
    {
        documents.MarkSaved(Document, savedState);
        metadataService.ClearCache();
        Saved?.Invoke(this, EventArgs.Empty);
        Changed?.Invoke(this, EventArgs.Empty);
    }

    private IReadOnlyDictionary<string, byte[]> prepareSaveOutputs() => prepareSaveOutputs(variables);

    private IReadOnlyDictionary<string, byte[]> prepareSaveOutputs(IReadOnlyList<GameVariableDefinition> captured)
    {
        string runtimeText = GameVariableLuaCodec.RenderRuntime(captured);
        string metadataText = GameVariableLuaCodec.RenderMetadata(captured);
        IReadOnlyList<GameVariableDefinition> parsed = GameVariableLuaCodec.Parse(
            runtimeText,
            metadataText,
            RuntimePath,
            MetadataPath);
        ensureEquivalent(parsed, captured);
        return new Dictionary<string, byte[]>(StringComparer.Ordinal)
        {
            [RuntimePath] = utf8.GetBytes(runtimeText),
            [MetadataPath] = utf8.GetBytes(metadataText),
        };
    }

    private GameVariableSaveResult commitMutation(int index = -1)
    {
        JsonObject data;
        if (index >= 0)
        {
            data = Document.InternalData!;
            ((JsonArray)data["variables"]!)[index] = serializeDefinition(variables[index]);
        }
        else
        {
            rebuildIndices();
            data = serializeVariables();
        }
        committing = true;
        try
        {
            documents.Commit(Document, data);
        }
        finally
        {
            committing = false;
        }
        return GameVariableSaveResult.Completed(string.Empty);
    }

    private JsonObject serializeVariables()
    {
        JsonArray definitions = [];
        foreach (GameVariableDefinition definition in variables)
            definitions.Add(serializeDefinition(definition));
        return new JsonObject { ["variables"] = definitions };
    }

    private static JsonObject serializeDefinition(GameVariableDefinition definition) => new()
    {
        ["name"] = definition.Name,
        ["type"] = (int)definition.Type,
        ["initialValue"] = definition.InitialValue,
        ["remark"] = definition.Remark,
    };

    private void onDocumentChanged(object? sender, EventArgs args)
    {
        if (!committing)
            readDocument();
        Changed?.Invoke(this, EventArgs.Empty);
    }

    private void readDocument()
    {
        variables.Clear();
        if (Document.InternalData?["variables"] is JsonArray definitions)
        {
            foreach (JsonNode? value in definitions)
            {
                if (value is not JsonObject definition)
                    continue;
                variables.Add(new GameVariableDefinition(
                    definition["name"]!.GetValue<string>(),
                    (GameVariableType)definition["type"]!.GetValue<int>(),
                    definition["initialValue"],
                    definition["remark"]!.GetValue<string>()));
            }
        }
        rebuildIndices();
    }

    private void rebuildIndices()
    {
        variableIndices.Clear();
        for (int index = 0; index < variables.Count; index++)
            variableIndices.Add(variables[index].Name, index);
    }

    private int findIndex(string name) => variableIndices.GetValueOrDefault(name, -1);

    private IReadOnlyList<GameVariableDefinition> loadExisting()
    {
        ensureOwned(RuntimePath);
        ensureOwned(MetadataPath);
        string runtimeText = File.ReadAllText(RuntimePath, utf8);
        string metadataText = File.ReadAllText(MetadataPath, utf8);
        return GameVariableLuaCodec.Parse(runtimeText, metadataText, RuntimePath, MetadataPath);
    }

    private void writePair(byte[] runtimeContent, byte[] metadataContent)
    {
        string directory = Path.GetDirectoryName(RuntimePath)
            ?? throw new InvalidOperationException(RuntimePath);
        Directory.CreateDirectory(directory);
        ensureOwnedIfPresent(RuntimePath);
        ensureOwnedIfPresent(MetadataPath);
        byte[]? runtimeOriginal = File.Exists(RuntimePath) ? File.ReadAllBytes(RuntimePath) : null;
        string runtimeTemp = FilePersistence.CreateTemporaryPath(RuntimePath);
        string metadataTemp = FilePersistence.CreateTemporaryPath(MetadataPath);
        bool runtimeReplaced = false;
        try
        {
            FilePersistence.WriteDurable(runtimeTemp, stream => stream.Write(runtimeContent));
            FilePersistence.WriteDurable(metadataTemp, stream => stream.Write(metadataContent));
            FilePersistence.MoveFile(runtimeTemp, RuntimePath, true);
            runtimeReplaced = true;
            FilePersistence.MoveFile(metadataTemp, MetadataPath, true);
        }
        catch (Exception exception) when (isFileException(exception))
        {
            if (runtimeReplaced)
            {
                try
                {
                    restore(RuntimePath, runtimeOriginal);
                }
                catch (Exception rollbackException) when (isFileException(rollbackException))
                {
                    throw new IOException(
                        exception.Message + "; rollback failed: " + rollbackException.Message,
                        exception);
                }
            }
            throw;
        }
        finally
        {
            deleteTemp(runtimeTemp);
            deleteTemp(metadataTemp);
        }
    }

    private static void restore(string path, byte[]? original)
    {
        if (original is null)
        {
            FilePersistence.DeleteFile(path);
            return;
        }
        string temp = FilePersistence.CreateTemporaryPath(path);
        try
        {
            FilePersistence.WriteDurable(temp, stream => stream.Write(original));
            FilePersistence.MoveFile(temp, path, true);
        }
        finally
        {
            deleteTemp(temp);
        }
    }

    private static void deleteTemp(string path)
    {
        try
        {
            FilePersistence.DeleteFile(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    private static void ensureOwnedIfPresent(string path)
    {
        if (File.Exists(path))
            ensureOwned(path);
    }

    private static void ensureOwned(string path)
    {
        using StreamReader reader = new(path, utf8, true);
        string? firstLine = reader.ReadLine();
        if (!string.Equals(firstLine, GeneratedMarker, StringComparison.Ordinal))
            throw new InvalidDataException($"{path} is not owned by the game variable manager");
    }

    private static void ensureEquivalent(IReadOnlyList<GameVariableDefinition> parsed, IReadOnlyList<GameVariableDefinition> expectedVariables)
    {
        if (parsed.Count != expectedVariables.Count)
            throw new InvalidDataException("Generated game variable files failed validation");
        for (int index = 0; index < expectedVariables.Count; index += 1)
        {
            GameVariableDefinition expected = expectedVariables[index];
            GameVariableDefinition actual = parsed[index];
            if (!string.Equals(expected.Name, actual.Name, StringComparison.Ordinal)
                || expected.Type != actual.Type
                || !valuesEquivalent(expected.InitialValue, actual.InitialValue)
                || !string.Equals(expected.Remark, actual.Remark, StringComparison.Ordinal))
            {
                throw new InvalidDataException("Generated game variable files failed validation");
            }
        }
    }

    private static JsonNode createDefault(GameVariableType type)
    {
        return type switch
        {
            GameVariableType.Bool => JsonValue.Create(false),
            GameVariableType.Int => JsonValue.Create(0),
            GameVariableType.Float => JsonValue.Create(0.0),
            GameVariableType.String => JsonValue.Create(string.Empty),
            GameVariableType.List => new JsonArray(),
            GameVariableType.Dict => new JsonObject(),
            _ => throw new InvalidDataException("Unsupported game variable type"),
        };
    }

    private static bool valuesEquivalent(JsonNode? left, JsonNode? right)
    {
        if (JsonNode.DeepEquals(left, right))
            return true;
        if (left is null || right is null)
            return false;
        if (left is JsonArray leftArray && right is JsonArray rightArray)
        {
            if (leftArray.Count != rightArray.Count)
                return false;
            for (int index = 0; index < leftArray.Count; index += 1)
            {
                if (!valuesEquivalent(leftArray[index], rightArray[index]))
                    return false;
            }
            return true;
        }
        if (left is JsonObject leftObject && right is JsonObject rightObject)
        {
            if (leftObject.Count != rightObject.Count)
                return false;
            foreach (KeyValuePair<string, JsonNode?> pair in leftObject)
            {
                if (!rightObject.TryGetPropertyValue(pair.Key, out JsonNode? rightValue)
                    || !valuesEquivalent(pair.Value, rightValue))
                {
                    return false;
                }
            }
            return true;
        }
        return left is JsonArray { Count: 0 } && right is JsonObject { Count: 0 }
            || left is JsonObject { Count: 0 } && right is JsonArray { Count: 0 };
    }

    private static string formatFailure(Exception exception)
    {
        return "GameVariables(" + exception.Message + ")";
    }

    private static bool isSaveException(Exception exception)
    {
        return isFileException(exception)
            || exception is InvalidDataException
            || exception is InterpreterException
            || exception is ArgumentException
            || exception is NotSupportedException;
    }

    private static bool isFileException(Exception exception)
    {
        return exception is IOException
            or UnauthorizedAccessException
            or SecurityException;
    }
}
