using Ludork.Models;
using Ludork.Plugin.Abstractions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json.Nodes;

namespace Ludork.Services;

internal sealed class GeneralEnumService
{
    internal const string TypesRuntimeRelativePath = "Scripts/Source/Configs/GeneralDataTypes.lua";
    internal const string TypesStubRelativePath = "Scripts/stub/Source/Configs/GeneralDataTypes.d.lua";
    private const string GeneratedMarker = "-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.";
    private const string AttributeSetModule = "GlobalCore";
    private readonly string projectPath;
    private static readonly UTF8Encoding utf8 = new(false, true);

    public GeneralEnumService(string projectPath)
    {
        this.projectPath = projectPath;
        TypesRuntimePath = Path.Combine(
            projectPath,
            TypesRuntimeRelativePath.Replace('/', Path.DirectorySeparatorChar));
        TypesStubPath = Path.Combine(
            projectPath,
            TypesStubRelativePath.Replace('/', Path.DirectorySeparatorChar));
    }

    public string TypesRuntimePath { get; }
    public string TypesStubPath { get; }

    internal IReadOnlyDictionary<string, byte[]> PrepareOutputs(IReadOnlyDictionary<string, JsonObject> generalData,
        ProjectEnumCatalog catalog)
    {
        IReadOnlyList<GeneralEnumType> types = buildTypes(generalData, catalog);
        Dictionary<string, byte[]> outputs = new(StringComparer.Ordinal)
        {
            [TypesRuntimePath] = utf8.GetBytes(renderTypesRuntime(types)),
            [TypesStubPath] = utf8.GetBytes(renderTypesStub(types)),
        };
        foreach (LuaEnumDefinition definition in catalog.Definitions.Values)
        {
            string name = definition.ModuleName.Split('.').Last();
            outputs[getEnumPath(definition.ModuleName)] = utf8.GetBytes(renderRuntime(definition.ModuleName, name,
                definition.Options.Select(option => new GeneralEnumMember(option.Value!.GetValue<string>(), option.Label))));
        }
        return outputs;
    }

    internal void AddToSaveBatch(EditorFileSaveBatch batch, IReadOnlyDictionary<string, JsonObject> generalData,
        ProjectEnumCatalog catalog)
    {
        IReadOnlyDictionary<string, byte[]> outputs = PrepareOutputs(generalData, catalog);
        foreach (KeyValuePair<string, byte[]> output in outputs)
            batch.Write(output.Key, output.Value);
        foreach (string path in getObsoletePaths(outputs.Keys))
            batch.Delete(path);
    }

    internal IReadOnlyList<string> GetOutputPaths(ProjectEnumCatalog catalog)
    {
        return catalog.Definitions.Keys.Select(getEnumPath).Concat([TypesRuntimePath, TypesStubPath]).ToArray();
    }

    internal bool NeedsGeneration(ProjectEnumCatalog catalog)
    {
        IReadOnlyList<string> paths = GetOutputPaths(catalog);
        return paths.Any(path => !File.Exists(path)) || getObsoletePaths(paths).Any();
    }

    private string getEnumPath(string module)
    {
        return Path.Combine(projectPath, "Scripts", module.Replace('.', Path.DirectorySeparatorChar) + ".lua");
    }

    private IEnumerable<string> getObsoletePaths(IEnumerable<string> outputPaths)
    {
        HashSet<string> expected = new(outputPaths, StringComparer.Ordinal);
        List<string> candidates =
        [
            Path.Combine(projectPath, "Scripts", "Source", "Configs", "GeneralEnum.lua"),
            Path.Combine(projectPath, "Scripts", "stub", "Source", "Configs", "GeneralEnum.d.lua"),
            Path.Combine(projectPath, "Scripts", "stub", "Enums", "GeneralDataKey.d.lua"),
        ];
        string[] directories =
        [
            Path.Combine(projectPath, "Scripts", "Enums", "GeneralData"),
            Path.Combine(projectPath, "Scripts", "stub", "Enums", "GeneralData"),
        ];
        foreach (string directory in directories)
        {
            if (Directory.Exists(directory))
                candidates.AddRange(Directory.EnumerateFiles(directory, "*.lua", SearchOption.TopDirectoryOnly));
        }
        foreach (string path in candidates)
        {
            if (!expected.Contains(path) && File.Exists(path)
                && File.ReadLines(path).Take(2).Any(line => line.Contains(
                    "AUTO-GENERATED by Ludork General Data. DO NOT EDIT.", StringComparison.Ordinal)))
            {
                yield return path;
            }
        }
    }

    private static IReadOnlyList<GeneralEnumType> buildTypes(IReadOnlyDictionary<string, JsonObject> generalData,
        ProjectEnumCatalog catalog)
    {
        List<GeneralEnumType> result = [];
        foreach ((string sourceKey, string module) in catalog.GeneralDataModules)
        {
            string typeName = module.Split('.').Last();
            JsonObject typeDefinition = generalData[sourceKey];
            List<GeneralDataAttribute> attributes = [];
            if (typeDefinition["params"] is JsonObject parameters)
            {
                foreach (KeyValuePair<string, JsonNode?> parameterEntry in parameters)
                {
                    if (parameterEntry.Value is not JsonObject definition)
                    {
                        throw new InvalidDataException(
                            $"General Data parameter {sourceKey}.{parameterEntry.Key} must be an object");
                    }
                    string? attributeType = readSchemaName(definition["type"]);
                    if (string.IsNullOrWhiteSpace(attributeType)
                        || !definition.TryGetPropertyValue("defaultValue", out JsonNode? defaultValue))
                    {
                        throw new InvalidDataException(
                            $"General Data parameter {sourceKey}.{parameterEntry.Key} requires type and defaultValue");
                    }
                    attributes.Add(new GeneralDataAttribute(
                        parameterEntry.Key,
                        attributeType,
                        defaultValue?.DeepClone(),
                        readSchemaName(definition["itemType"]),
                        readSchemaName(definition["valueType"])));
                }
            }
            result.Add(new GeneralEnumType(sourceKey, typeName + "AttributeSet", attributes));
        }
        return result;
    }

    private static string renderRuntime(string moduleName, string typeName, IEnumerable<GeneralEnumMember> entries)
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker).Append("\n\n")
            .Append("---@enum ").Append(moduleName).Append("\n")
            .Append("local ").Append(typeName).Append(" = {\n");
        appendEntries(builder, entries);
        builder.Append("}\n\nreturn ").Append(typeName).Append("\n");
        return builder.ToString();
    }

    private static string renderTypesRuntime(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append(GeneratedMarker)
            .Append("\nlocal AttributeSet = require(")
            .Append(LuaStringLiteral.Quote(AttributeSetModule))
            .Append(").AttributeSet\n\n")
            .Append("---@param self GlobalCore.AttributeSet\n")
            .Append("---@param values? table<string, any>\n")
            .Append("---@param stored? boolean\n")
            .Append("local function initAttributeSet(self, values, stored)\n")
            .Append("    AttributeSet.init(self)\n")
            .Append("    if stored == true then\n")
            .Append("        self:initializeStored(values or {})\n")
            .Append("    else\n")
            .Append("        self:initialize(values or {})\n")
            .Append("    end\n")
            .Append("end\n");
        foreach (GeneralEnumType type in types)
        {
            builder.Append('\n');
            appendAttributeSetRuntime(builder, type);
        }
        builder.Append("\nlocal Types = {\n");
        for (int index = 0; index < types.Count; index++)
        {
            GeneralEnumType type = types[index];
            builder.Append("    [")
                .Append(LuaStringLiteral.Quote(type.SourceKey))
                .Append("] = ")
                .Append(type.AttributeSetName);
            if (index != types.Count - 1)
                builder.Append(',');
            builder.Append('\n');
        }
        builder.Append("}\n\nlocal GeneralDataTypes = {\n")
            .Append("    Types = Types,\n");
        for (int index = 0; index < types.Count; index++)
        {
            GeneralEnumType type = types[index];
            builder.Append("    ")
                .Append(type.AttributeSetName)
                .Append(" = ")
                .Append(type.AttributeSetName);
            if (index != types.Count - 1)
                builder.Append(',');
            builder.Append('\n');
        }
        builder.Append("}\n\n")
            .Append("function GeneralDataTypes.Create(typeName, memberId, memberData)\n")
            .Append("    assert(rawget(Types, typeName) ~= nil, \"General Data type not found: \" .. tostring(typeName))\n")
            .Append("    local attributeType = Types[typeName]\n")
            .Append("    assert(type(memberId) == \"string\", \"General Data member ID must be a string\")\n")
            .Append("    assert(type(memberData) == \"table\", \"General Data member must be a table\")\n")
            .Append("    ---@type table<string, any>\n")
            .Append("    local values = { ID = deepcopy(memberId) }\n")
            .Append("    for _, name in ipairs(attributeType.ATTRIBUTE_NAMES) do\n")
            .Append("        local value = rawget(memberData, name)\n")
            .Append("        if value ~= nil then\n")
            .Append("            values[name] = deepcopy(value)\n")
            .Append("        end\n")
            .Append("    end\n")
            .Append("    return attributeType.new(values, true)\n")
            .Append("end\n\n")
            .Append("return GeneralDataTypes\n");
        return builder.ToString();
    }

    private static void appendAttributeSetRuntime(StringBuilder builder, GeneralEnumType type)
    {
        builder.Append("local ").Append(type.AttributeSetName).Append(" = {}\n");
        if (type.Attributes.Count == 0)
        {
            builder.Append(type.AttributeSetName).Append(".ATTRIBUTE_NAMES = {}\n");
        }
        else
        {
            string names = string.Join(", ", type.Attributes.Select(attribute => LuaStringLiteral.Quote(attribute.Name)));
            string singleLine = type.AttributeSetName + ".ATTRIBUTE_NAMES = { " + names + " }";
            if (singleLine.Length <= 120)
            {
                builder.Append(singleLine).Append('\n');
            }
            else
            {
                builder.Append(type.AttributeSetName)
                    .Append(".ATTRIBUTE_NAMES = {\n    ")
                    .Append(names)
                    .Append("\n}\n");
            }
        }
        builder.Append(type.AttributeSetName).Append(".SCHEMA = {");
        if (type.Attributes.Count == 0)
        {
            builder.Append("}\n");
        }
        else
        {
            builder.Append('\n');
            for (int index = 0; index < type.Attributes.Count; index++)
            {
                GeneralDataAttribute attribute = type.Attributes[index];
                builder.Append("    ");
                appendLuaTableKey(builder, attribute.Name);
                builder.Append(" = { type = ");
                JsonNode typeSchema = attribute.Type switch
                {
                    "list" => new JsonObject { ["list"] = LuaMetadataType.Parse(attribute.ItemType ?? "any").ToSchema() },
                    "dict" => new JsonObject { ["dict"] = LuaMetadataType.Parse(attribute.ValueType ?? "any").ToSchema() },
                    _ => LuaMetadataType.Parse(attribute.Type).ToSchema(),
                };
                appendLuaValue(builder, typeSchema);
                builder.Append(", default = ");
                appendLuaValue(builder, attribute.DefaultValue);
                builder.Append(" }");
                if (index != type.Attributes.Count - 1)
                    builder.Append(',');
                builder.Append('\n');
            }
            builder.Append("}\n");
        }
        builder.Append(type.AttributeSetName)
            .Append(".init = initAttributeSet\n")
            .Append(type.AttributeSetName)
            .Append(" = class(")
            .Append(type.AttributeSetName)
            .Append(", AttributeSet)\n");
    }

    private static string renderTypesStub(IReadOnlyList<GeneralEnumType> types)
    {
        StringBuilder builder = new();
        builder.Append("---@meta Source.Configs.GeneralDataTypes\n")
            .Append("--- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.\n\n");
        foreach (GeneralEnumType type in types)
        {
            string qualifiedName = "Source.Configs.GeneralDataTypes." + type.AttributeSetName;
            builder.Append("---@class ").Append(qualifiedName).Append(": GlobalCore.AttributeSet\n");
            List<LuaDocField> fields =
            [
                new LuaDocField("ID", "string"),
                new LuaDocField("ATTRIBUTE_NAMES", "string[]"),
                new LuaDocField("SCHEMA", "table<string, { type: string|table, default: any }>"),
            ];
            foreach (GeneralDataAttribute attribute in type.Attributes)
                fields.Add(new LuaDocField(luaDocFieldName(attribute.Name), luaDocType(attribute)));
            appendAlignedLuaDocFields(builder, fields);
            builder.Append("---@type ")
                .Append(qualifiedName)
                .Append(" & Class.ClassType<")
                .Append(qualifiedName)
                .Append(">\n")
                .Append("local ")
                .Append(type.AttributeSetName)
                .Append(" = {}\n\n");
        }
        builder.Append("---@class Source.Configs.GeneralDataTypes.Module\n");
        List<LuaDocField> moduleFields =
        [
            new LuaDocField("Types", "table<string, Class.ClassType<GlobalCore.AttributeSet>>"),
        ];
        foreach (GeneralEnumType type in types)
        {
            string qualifiedName = "Source.Configs.GeneralDataTypes." + type.AttributeSetName;
            moduleFields.Add(new LuaDocField(
                type.AttributeSetName,
                qualifiedName + " & Class.ClassType<" + qualifiedName + ">"));
        }
        appendAlignedLuaDocFields(builder, moduleFields);
        builder.Append("local GeneralDataTypes = {}\n\n");
        appendAlignedLuaDocParameters(
            builder,
            [
                new LuaDocField("typeName", "string"),
                new LuaDocField("memberId", "string"),
                new LuaDocField("memberData", "table<string, any>"),
            ]);
        builder
            .Append("---@return GlobalCore.AttributeSet\n")
            .Append("function GeneralDataTypes.Create(typeName, memberId, memberData) end\n\n")
            .Append("return GeneralDataTypes\n");
        return builder.ToString();
    }

    private static void appendAlignedLuaDocFields(StringBuilder builder, IReadOnlyList<LuaDocField> fields)
    {
        int width = fields.Max(field => field.Name.Length);
        foreach (LuaDocField field in fields)
        {
            builder.Append("---@field ")
                .Append(field.Name.PadRight(width))
                .Append(' ')
                .Append(field.Type)
                .Append('\n');
        }
    }

    private static void appendAlignedLuaDocParameters(StringBuilder builder, IReadOnlyList<LuaDocField> parameters)
    {
        int width = parameters.Max(parameter => parameter.Name.Length);
        foreach (LuaDocField parameter in parameters)
        {
            builder.Append("---@param ")
                .Append(parameter.Name.PadRight(width))
                .Append(' ')
                .Append(parameter.Type)
                .Append('\n');
        }
    }

    private static string luaDocType(GeneralDataAttribute attribute)
    {
        return attribute.Type switch
        {
            "bool" => "boolean",
            "int" => "integer",
            "float" => "number",
            "string" or "file" => "string",
            "list" => luaDocSchema(LuaMetadataType.Parse(new JsonObject { ["list"] = LuaMetadataType.Parse(attribute.ItemType ?? "any").ToSchema() })),
            "dict" => "table<string, " + luaDocScalarType(attribute.ValueType) + ">",
            _ => luaDocScalarType(attribute.Type),
        };
    }

    private static string? readSchemaName(JsonNode? value)
    {
        if (value is JsonValue scalar && scalar.TryGetValue(out string? name))
            return name;
        return value is null ? null : LuaMetadataType.Parse(value).ToString();
    }

    private static string luaDocScalarType(string? type)
    {
        return luaDocSchema(LuaMetadataType.Parse(type ?? "any"));
    }

    private static string luaDocSchema(LuaMetadataType type)
    {
        return type.Kind switch
        {
            LuaMetadataTypeKind.Union => string.Join("|", type.Arguments.Select(luaDocSchema)),
            LuaMetadataTypeKind.List => (type.Arguments[0].Kind == LuaMetadataTypeKind.Union
                ? "(" + luaDocSchema(type.Arguments[0]) + ")" : luaDocSchema(type.Arguments[0])) + "[]",
            LuaMetadataTypeKind.Dictionary => "table<" + luaDocSchema(type.Arguments[0]) + ", " + luaDocSchema(type.Arguments[1]) + ">",
            LuaMetadataTypeKind.Tuple => "{ " + string.Join(", ", type.Arguments.Select((item, index) => $"[{index + 1}]: {luaDocSchema(item)}")) + " }",
            _ => type.Name switch
            {
                "bool" => "boolean",
                "int" => "integer",
                "float" => "number",
                "string" or "file" => "string",
                _ => type.Name,
            },
        };
    }

    private static string luaDocFieldName(string name)
    {
        return LuaIdentifier.IsValid(name) ? name : "[" + LuaStringLiteral.Quote(name) + "]";
    }

    private static void appendLuaTableKey(StringBuilder builder, string key)
    {
        if (LuaIdentifier.IsValid(key))
            builder.Append(key);
        else
            builder.Append('[').Append(LuaStringLiteral.Quote(key)).Append(']');
    }

    private static void appendLuaValue(StringBuilder builder, JsonNode? value)
    {
        if (value is null)
        {
            builder.Append("nil");
            return;
        }
        if (value is JsonArray array)
        {
            builder.Append('{');
            for (int index = 0; index < array.Count; index++)
            {
                if (index != 0)
                    builder.Append(", ");
                appendLuaValue(builder, array[index]);
            }
            builder.Append('}');
            return;
        }
        if (value is JsonObject obj)
        {
            builder.Append('{');
            int index = 0;
            foreach (KeyValuePair<string, JsonNode?> entry in obj)
            {
                if (index != 0)
                    builder.Append(", ");
                appendLuaTableKey(builder, entry.Key);
                builder.Append(" = ");
                appendLuaValue(builder, entry.Value);
                index++;
            }
            builder.Append('}');
            return;
        }
        JsonValue scalar = (JsonValue)value;
        if (scalar.TryGetValue(out string? stringValue))
            builder.Append(LuaStringLiteral.Quote(stringValue));
        else if (scalar.TryGetValue(out bool boolValue))
            builder.Append(boolValue ? "true" : "false");
        else if (scalar.TryGetValue(out long longValue))
            builder.Append(longValue.ToString(CultureInfo.InvariantCulture));
        else if (scalar.TryGetValue(out double doubleValue))
            builder.Append(doubleValue.ToString("R", CultureInfo.InvariantCulture));
        else
            throw new InvalidDataException("Unsupported General Data default value");
    }

    private static void appendEntries(StringBuilder builder, IEnumerable<GeneralEnumMember> entries)
    {
        foreach (GeneralEnumMember entry in entries)
        {
            builder.Append("    ")
                .Append(entry.Identifier)
                .Append(" = ")
                .Append(LuaStringLiteral.Quote(entry.SourceKey))
                .Append(",\n");
        }
    }

    private sealed record GeneralEnumType(
        string SourceKey,
        string AttributeSetName,
        IReadOnlyList<GeneralDataAttribute> Attributes);

    private sealed record GeneralEnumMember(string SourceKey, string Identifier);

    private sealed record GeneralDataAttribute(
        string Name,
        string Type,
        JsonNode? DefaultValue,
        string? ItemType,
        string? ValueType);

    private sealed record LuaDocField(string Name, string Type);

}
