# -*- encoding: utf-8 -*-

DATA_FORMAT_JSON = "json"
DATA_FORMAT_DAT = "dat"

DATA_FORMAT_EXTENSIONS = {
    DATA_FORMAT_JSON: ".json",
    DATA_FORMAT_DAT: ".dat",
}
DATA_FORMAT_LABELS = {
    DATA_FORMAT_JSON: "JSON",
    DATA_FORMAT_DAT: "DAT",
}
DATA_FORMATS = tuple(DATA_FORMAT_EXTENSIONS.keys())
DATA_FILE_EXTENSIONS = (
    DATA_FORMAT_EXTENSIONS[DATA_FORMAT_JSON],
    DATA_FORMAT_EXTENSIONS[DATA_FORMAT_DAT],
)
DATA_FILE_EXTENSIONS_DAT_FIRST = (
    DATA_FORMAT_EXTENSIONS[DATA_FORMAT_DAT],
    DATA_FORMAT_EXTENSIONS[DATA_FORMAT_JSON],
)
DATA_FILE_SUFFIXES = tuple(ext[1:] for ext in DATA_FILE_EXTENSIONS)
DATA_FILE_DIALOG_FILTER = "JSON (*.json);;DAT (*.dat)"
