-- Generated by ScriptTools ui-assets generate. Do not edit.
---@meta Source.Windows.WindowMenu

---@brief In-game menu window that manages commands, open/close triggers, and sub-windows.
---
--- Owns the full menu lifecycle: detects the open trigger, defines built-in commands
--- (Items, Equipment, Save, Config, Return to Title), delegates to WindowItem, and
--- re-enables player movement on close.
---@class Source.Windows.WindowMenu: Source.Windows.Base.WindowSelectable, Source.UIBase.Ui.Window
---@field ui Source.UI.WindowMenu
local Window = {}

---@brief Construct the menu window and wire up sub-window callbacks.
---
--- - @param player The player actor; movement is disabled while the menu is open.
--- - @param windows Named item, equipment, and non-load-only save/load windows.
---@param player  Source.Player.Player
---@param windows Source.Windows.WindowMenuWindows
---@return Source.Windows.WindowMenu
function Window.new(player, windows) end

---@brief Construct the menu window and wire up sub-window callbacks.
---
--- - @param player The player actor; movement is disabled while the menu is open.
--- - @param windows Named item, equipment, and non-load-only save/load windows.
---@param player  Source.Player.Player
---@param windows Source.Windows.WindowMenuWindows
---@param ui      Source.UI.WindowMenu
---@return Source.Windows.WindowMenu
function Window.FromView(ui, player, windows) end

---@param owner Source.Windows.WindowMenu
---@return Source.UIBase.CommandRow.Controller.Model[]
function Window.CreateCommands(owner) end

---@param commands Source.UIBase.CommandRow.Controller.Model[]
function Window:attach(commands) end

function Window:bind() end

---@brief Close the menu window and restore player movement.
---@param onHidden function | nil
function Window:close(onHidden) end

function Window:exitGame() end

---@return Source.Player.Player
function Window:getPlayer() end

function Window:handleCancel() end

---@return boolean
---@param direction string
function Window:handleDirectionalKey(direction) end

---@return boolean
---@param kwargs Engine.UiInputEventArguments
function Window:handleMouseButtonDown(kwargs) end

---@brief Return True when the menu or its sub-windows are blocking map input.
---@return boolean
function Window:isBlocking() end

---@brief Reactivate the command list and return focus after the Config window closes.
function Window:onConfigClose() end

---@brief Move menu cursor or jump to the currently opened submenu.
---
--- - @param direction Navigation direction.
---
--- - @return True if the direction was handled.
---@param direction string
---@return boolean
function Window:onDirectionalKey(direction) end

function Window:onMenuExit() end

---@brief Handle cancel key to close the menu.
---
--- - @param kwargs Event data.
---@brief Handle right-click cancel to close the menu.
---@param kwargs Engine.UiInputEventArguments
---@return boolean
function Window:onMouseButtonDown(kwargs) end

function Window:onReturn() end

function Window:onSaveLoadClose() end

---@param deltaTime number
function Window:onTick(deltaTime) end

---@brief Open the menu window at its first command and disable player movement.
function Window:open() end

function Window:openConfig() end

function Window:openEquipment() end

function Window:openInventory() end

function Window:openSaveLoad() end

function Window:refreshRows() end

---@brief Set a predicate that decides whether close restores player movement.
---
--- - @param guard Callable returning True when movement may be restored.
---@param guard function
function Window:setMoveRestoreGuard(guard) end

---@brief Rebind the player whose movement is controlled by the menu.
---@param player Source.Player.Player
function Window:setPlayer(player) end

function Window:tick() end

return Window
