# -*- encoding: utf-8 -*-
from __future__ import annotations

import os
from datetime import datetime
from typing import Optional

from .parser import (
    ParsedHeader,
    ClassInfo,
    FunctionInfo,
    MethodInfo,
    PropertyInfo,
    ConstructorInfo,
    ParamInfo,
    BindAnnotation,
)


def _escape_docstring(text: str) -> str:
    if not text:
        return ""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_py_arg(param: ParamInfo) -> str:
    if param.default_value is not None:
        return f'py::arg("{param.name}") = {param.default_value}'
    return f'py::arg("{param.name}")'


def _format_py_args(params: list[ParamInfo]) -> str:
    if not params:
        return ""
    args = [_format_py_arg(p) for p in params]
    return ", " + ", ".join(args)


def _get_docstring_arg(annotation: Optional[BindAnnotation]) -> str:
    if annotation and annotation.docstring:
        escaped = _escape_docstring(annotation.docstring)
        return f', "{escaped}"'
    return ""


def _get_return_policy(annotation: Optional[BindAnnotation]) -> str:
    if annotation and annotation.options.get("return_policy"):
        policy = annotation.options["return_policy"]
        return f", py::return_value_policy::{policy}"
    return ""


class BindingCodegen:
    def __init__(self, module_name: str, internals_id: str = "PYSF"):
        self.module_name = module_name
        self.internals_id = internals_id
        self._lines: list[str] = []
        self._indent = 0

    def _emit(self, line: str = ""):
        if line:
            self._lines.append("    " * self._indent + line)
        else:
            self._lines.append("")

    def _indent_inc(self):
        self._indent += 1

    def _indent_dec(self):
        self._indent -= 1

    def generate(
        self,
        headers: list[ParsedHeader],
        pysf_import: Optional[str] = None,
        extra_includes: list[str] = None,
        include_base_dir: Optional[str] = None,
    ) -> str:
        self._lines = []
        self._indent = 0

        self._emit("// ============================================================================")
        self._emit(f"// AUTO-GENERATED by Ludork Bindgen - DO NOT EDIT")
        self._emit(f"// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self._emit("// ============================================================================")
        self._emit()
        self._emit(f'#define PYBIND11_INTERNALS_ID "{self.internals_id}"')
        self._emit()
        self._emit("#include <pybind11/pybind11.h>")
        self._emit("#include <pybind11/stl.h>")
        self._emit("#include <pybind11/functional.h>")
        self._emit()
        self._emit("#include <iostream>")
        self._emit()

        if extra_includes:
            for inc in extra_includes:
                self._emit(f"#include {inc}")
            self._emit()

        all_includes = set()
        for header in headers:
            if include_base_dir:
                rel_path = os.path.relpath(header.filepath, include_base_dir).replace("\\", "/")
            else:
                rel_path = os.path.basename(header.filepath)
            all_includes.add(f'#include "{rel_path}"')

        for inc in sorted(all_includes):
            self._emit(inc)
        self._emit()

        self._emit("namespace py = pybind11;")
        self._emit()

        self._emit(f"PYBIND11_MODULE({self.module_name}, m) {{")
        self._indent_inc()

        self._emit(
            "void *internals_ptr = static_cast<void *>("
            "const_cast<py::detail::internals *>(&py::detail::get_internals()));"
        )
        self._emit(
            f'std::cout << "[Ludork {self.module_name} Binding] '
            f'PyBind11 internals address: " << internals_ptr << std::endl;'
        )
        self._emit()

        if pysf_import:
            self._emit('auto importModule = py::module::import("importlib").attr("import_module");')
            self._emit("try {")
            self._indent_inc()
            self._emit(f'importModule("{pysf_import}");')
            self._indent_dec()
            self._emit("} catch (py::error_already_set &) {")
            self._indent_inc()
            self._emit("PyErr_Clear();")
            self._emit('importModule("pysf");')
            self._indent_dec()
            self._emit("}")
            self._emit()

        all_classes: list[ClassInfo] = []
        all_functions: list[tuple[str, FunctionInfo]] = []

        for header in headers:
            for cls in header.classes:
                all_classes.append(cls)
            for func in header.functions:
                all_functions.append((os.path.basename(header.filepath), func))

        sorted_classes = self._topo_sort_classes(all_classes)

        if all_functions:
            current_header = None
            for header_name, func in all_functions:
                if header_name != current_header:
                    self._emit(f"// --- From: {header_name} ---")
                    self._emit()
                    current_header = header_name
                self._gen_function(func)

        for cls in sorted_classes:
            self._gen_class(cls)
            self._emit()

        self._indent_dec()
        self._emit("}")
        self._emit()

        return "\n".join(self._lines)

    def _topo_sort_classes(self, classes: list[ClassInfo]) -> list[ClassInfo]:
        class_names = {cls.name for cls in classes}
        class_map = {cls.name: cls for cls in classes}

        visited: set[str] = set()
        result: list[ClassInfo] = []

        def visit(name: str):
            if name in visited:
                return
            visited.add(name)
            cls = class_map[name]
            for base in cls.bases:
                pure_base = base.split("::")[-1] if "::" in base else base
                if pure_base in class_names:
                    visit(pure_base)
            result.append(cls)

        for cls in classes:
            visit(cls.name)

        return result

    def _gen_class(self, cls: ClassInfo):
        bind_name = cls.annotation.options.get("module_name", cls.name) if cls.annotation else cls.name

        if cls.bases:
            base_args = ", " + ", ".join(cls.bases)
        else:
            base_args = ""

        docstring = _get_docstring_arg(cls.annotation)

        var_name = f"{cls.name}Class"
        self._emit(
            f"py::class_<{cls.name}{base_args}> {var_name}"
            f'(m, "{bind_name}"{docstring});'
        )

        if cls.constructors:
            for ctor in cls.constructors:
                self._gen_constructor(var_name, cls, ctor)
        elif not cls.has_deleted_default_ctor:
            self._emit(f"{var_name}.def(py::init<>());")

        for method in cls.methods:
            self._gen_method(var_name, cls, method)

        for prop in cls.properties:
            self._gen_property(var_name, cls, prop)

    def _gen_constructor(self, var_name: str, cls: ClassInfo, ctor: ConstructorInfo):
        if not ctor.params:
            docstring = _get_docstring_arg(ctor.annotation)
            self._emit(f"{var_name}.def(py::init<>(){docstring});")
        else:
            type_args = ", ".join(p.type_spelling for p in ctor.params)
            py_args = _format_py_args(ctor.params)
            docstring = _get_docstring_arg(ctor.annotation)
            self._emit(
                f"{var_name}.def(py::init<{type_args}>()"
                f"{py_args}{docstring});"
            )

    def _gen_method(self, var_name: str, cls: ClassInfo, method: MethodInfo):
        py_args = _format_py_args(method.params)
        docstring = _get_docstring_arg(method.annotation)
        return_policy = _get_return_policy(method.annotation)

        if method.is_overloaded:
            param_types = ", ".join(p.type_spelling for p in method.params)
            const_suffix = " const" if method.is_const else ""
            cast = (
                f"static_cast<{method.return_type} ({cls.name}::*)"
                f"({param_types}){const_suffix}>"
                f"(&{cls.name}::{method.name})"
            )
            self._emit(
                f'{var_name}.def("{method.name}", {cast}'
                f"{py_args}{return_policy}{docstring});"
            )
        elif method.is_static:
            self._emit(
                f'{var_name}.def_static("{method.name}", '
                f"&{cls.name}::{method.name}"
                f"{py_args}{return_policy}{docstring});"
            )
        else:
            self._emit(
                f'{var_name}.def("{method.name}", '
                f"&{cls.name}::{method.name}"
                f"{py_args}{return_policy}{docstring});"
            )

    def _gen_property(self, var_name: str, cls: ClassInfo, prop: PropertyInfo):
        docstring = _get_docstring_arg(prop.annotation)
        if prop.is_readonly:
            self._emit(
                f'{var_name}.def_readonly("{prop.name}", '
                f"&{cls.name}::{prop.name}{docstring});"
            )
        else:
            self._emit(
                f'{var_name}.def_readwrite("{prop.name}", '
                f"&{cls.name}::{prop.name}{docstring});"
            )

    def _gen_function(self, func: FunctionInfo):
        py_args = _format_py_args(func.params)
        docstring = _get_docstring_arg(func.annotation)
        return_policy = _get_return_policy(func.annotation)

        if func.is_overloaded:
            param_names = ", ".join(p.name for p in func.params)
            lambda_params = ", ".join(
                f"{p.type_spelling} {p.name}" for p in func.params
            )
            self._emit(
                f'm.def("{func.name}", '
                f"[]({lambda_params}) {{ return {func.name}({param_names}); }}"
                f"{py_args}{return_policy}{docstring});"
            )
        else:
            self._emit(
                f'm.def("{func.name}", &{func.name}'
                f"{py_args}{return_policy}{docstring});"
            )


class CMakeGen:
    def __init__(self, project_name: str):
        self.project_name = project_name

    def generate(
        self,
        source_files: list[str],
        generated_binding: str,
        needs_sfml: bool = False,
        extra_include_dirs: list[str] = None,
    ) -> str:
        lines = [
            "# ============================================================================",
            f"# AUTO-GENERATED by Ludork Bindgen - DO NOT EDIT",
            f"# Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "# ============================================================================",
            "",
            f"project({self.project_name})",
            "",
        ]

        all_sources = [f'"{generated_binding}"'] + [f'"{s}"' for s in source_files]
        lines.append(f"pybind11_add_module({self.project_name}")
        for src in all_sources:
            lines.append(f"    {src}")
        lines.append(")")
        lines.append("")

        lines.append(f"ConfigureTarget({self.project_name})")

        if needs_sfml:
            lines.append(f"ConfigureSFMLTarget({self.project_name})")

        if extra_include_dirs:
            lines.append("")
            for inc_dir in extra_include_dirs:
                lines.append(f"target_include_directories({self.project_name} PRIVATE")
                lines.append(f'    "{inc_dir}"')
                lines.append(")")

        lines.append("")
        return "\n".join(lines)
