# -*- encoding: utf-8 -*-
from __future__ import annotations

import os
import re
from datetime import datetime
from typing import Optional

from .parser import (
    ParsedHeader,
    ClassInfo,
    FunctionInfo,
    MethodInfo,
    PropertyInfo,
    ConstructorInfo,
    ParamInfo,
    BindAnnotation,
)


def _escape_docstring(text: str) -> str:
    if not text:
        return ""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _type_references_class(type_spelling: str, class_name: str) -> bool:
    return re.search(rf"(?<!\w){re.escape(class_name)}(?!\w)", type_spelling) is not None


def _format_py_arg_display_default(param: ParamInfo) -> str:
    default_value = param.default_value or ""
    type_spelling = param.type_spelling
    if re.search(r"\b(std::)?vector\s*<", type_spelling):
        return "[]"
    if re.search(r"\b(std::)?array\s*<", type_spelling):
        return "()"
    return default_value


def _format_py_arg(param: ParamInfo, class_names: Optional[set[str]] = None) -> str:
    if param.default_value is not None:
        if class_names and any(_type_references_class(param.type_spelling, class_name) for class_name in class_names):
            escaped_default = _escape_docstring(_format_py_arg_display_default(param))
            return f'py::arg_v("{param.name}", {param.default_value}, "{escaped_default}")'
        return f'py::arg("{param.name}") = {param.default_value}'
    return f'py::arg("{param.name}")'


def _format_py_args(params: list[ParamInfo], class_names: Optional[set[str]] = None) -> str:
    if not params:
        return ""
    args = [_format_py_arg(p, class_names) for p in params]
    return ", " + ", ".join(args)


def _get_docstring_arg(annotation: Optional[BindAnnotation]) -> str:
    if annotation and annotation.docstring:
        escaped = _escape_docstring(annotation.docstring)
        return f', "{escaped}"'
    return ""


def _get_return_policy(annotation: Optional[BindAnnotation]) -> str:
    if annotation and annotation.options.get("return_policy"):
        policy = annotation.options["return_policy"]
        return f", py::return_value_policy::{policy}"
    return ""


def _is_copyable_class(cls: ClassInfo) -> bool:
    if not cls.annotation:
        return False
    return cls.annotation.options.get("copyable") is True


def _format_py_literal(value) -> str:
    if value is True:
        return "py::bool_(true)"
    if value is False:
        return "py::bool_(false)"
    if value is None:
        return "py::none()"

    text = str(value)
    if text == "None":
        return "py::none()"
    if re.fullmatch(r"-?\d+", text):
        return f"py::int_({text})"
    if re.fullmatch(r"-?\d+\.\d+", text):
        return f"py::float_({text})"
    return f'py::str("{_escape_docstring(text)}")'


def _format_split_literal(value) -> str:
    if value is True:
        return "py::make_tuple(py::bool_(true))"
    if value is False:
        return "py::make_tuple(py::bool_(false))"
    if value is None or str(value) == "None":
        return "py::make_tuple(py::none())"
    return f"py::make_tuple({_format_py_literal(value)})"


class BindingCodegen:
    def __init__(self, module_name: str, internals_id: str = "PYSF"):
        self.module_name = module_name
        self.internals_id = internals_id
        self._lines: list[str] = []
        self._indent = 0
        self._class_names: set[str] = set()
        self._metadata_counter = 0

    def _emit(self, line: str = ""):
        if line:
            self._lines.append("    " * self._indent + line)
        else:
            self._lines.append("")

    def _indent_inc(self):
        self._indent += 1

    def _indent_dec(self):
        self._indent -= 1

    def generate(
        self,
        headers: list[ParsedHeader],
        pysf_import: Optional[str] = None,
        extra_includes: list[str] = None,
        include_base_dir: Optional[str] = None,
    ) -> str:
        self._lines = []
        self._indent = 0
        self._metadata_counter = 0

        self._emit("// ============================================================================")
        self._emit(f"// AUTO-GENERATED by Ludork Bindgen - DO NOT EDIT")
        self._emit(f"// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self._emit("// ============================================================================")
        self._emit()
        self._emit(f'#define PYBIND11_INTERNALS_ID "{self.internals_id}"')
        self._emit()
        self._emit("#include <pybind11/pybind11.h>")
        self._emit("#include <pybind11/stl.h>")
        self._emit("#include <pybind11/functional.h>")
        self._emit()
        self._emit("#include <iostream>")
        self._emit()

        if extra_includes:
            for inc in extra_includes:
                self._emit(f"#include {inc}")
            self._emit()

        all_includes = set()
        for header in headers:
            if include_base_dir:
                rel_path = os.path.relpath(header.filepath, include_base_dir).replace("\\", "/")
            else:
                rel_path = os.path.basename(header.filepath)
            all_includes.add(f'#include "{rel_path}"')

        for inc in sorted(all_includes):
            self._emit(inc)
        self._emit()

        self._emit("namespace py = pybind11;")
        self._emit()

        self._emit(f"PYBIND11_MODULE({self.module_name}, m) {{")
        self._indent_inc()

        self._emit(
            "void *internals_ptr = static_cast<void *>("
            "const_cast<py::detail::internals *>(&py::detail::get_internals()));"
        )
        self._emit(
            f'std::cout << "[Ludork {self.module_name} Binding] '
            f'PyBind11 internals address: " << internals_ptr << std::endl;'
        )
        self._emit()

        if pysf_import:
            self._emit('auto importModule = py::module::import("importlib").attr("import_module");')
            self._emit("try {")
            self._indent_inc()
            self._emit(f'importModule("{pysf_import}");')
            self._indent_dec()
            self._emit("} catch (py::error_already_set &) {")
            self._indent_inc()
            self._emit("PyErr_Clear();")
            self._emit('importModule("pysf");')
            self._indent_dec()
            self._emit("}")
            self._emit()

        all_classes: list[ClassInfo] = []
        all_functions: list[tuple[str, FunctionInfo]] = []

        for header in headers:
            for cls in header.classes:
                all_classes.append(cls)
            for func in header.functions:
                all_functions.append((os.path.basename(header.filepath), func))

        self._class_names = {cls.name for cls in all_classes}
        sorted_classes = self._topo_sort_classes(all_classes)

        if all_functions:
            current_header = None
            for header_name, func in all_functions:
                if header_name != current_header:
                    self._emit(f"// --- From: {header_name} ---")
                    self._emit()
                    current_header = header_name
                self._gen_function(func)

        for cls in sorted_classes:
            self._gen_class(cls)
            self._emit()

        self._indent_dec()
        self._emit("}")
        self._emit()

        return "\n".join(self._lines)

    def _topo_sort_classes(self, classes: list[ClassInfo]) -> list[ClassInfo]:
        class_names = {cls.name for cls in classes}
        class_map = {cls.name: cls for cls in classes}

        visited: set[str] = set()
        visiting: set[str] = set()
        result: list[ClassInfo] = []

        def dependency_names(cls: ClassInfo) -> list[str]:
            deps: list[str] = []
            for base in cls.bases:
                pure_base = base.split("::")[-1] if "::" in base else base
                if pure_base in class_names and pure_base != cls.name:
                    deps.append(pure_base)

            for ctor in cls.constructors:
                for param in ctor.params:
                    if param.default_value is None:
                        continue
                    for class_name in class_names:
                        if class_name == cls.name:
                            continue
                        if _type_references_class(param.type_spelling, class_name):
                            deps.append(class_name)

            return deps

        def visit(name: str):
            if name in visited:
                return
            if name in visiting:
                return
            visiting.add(name)
            visited.add(name)
            cls = class_map[name]
            for dependency_name in dependency_names(cls):
                visit(dependency_name)
            visiting.remove(name)
            result.append(cls)

        for cls in classes:
            visit(cls.name)

        return result

    def _gen_class(self, cls: ClassInfo):
        bind_name = cls.annotation.options.get("module_name", cls.name) if cls.annotation else cls.name

        if cls.bases:
            base_args = ", " + ", ".join(cls.bases)
        else:
            base_args = ""

        docstring = _get_docstring_arg(cls.annotation)

        var_name = f"{cls.name}Class"
        self._emit(
            f"py::class_<{cls.name}{base_args}> {var_name}"
            f'(m, "{bind_name}"{docstring});'
        )
        self._gen_metadata(var_name, cls.annotation)

        if cls.constructors:
            for ctor in cls.constructors:
                self._gen_constructor(var_name, cls, ctor)
        elif not cls.has_deleted_default_ctor:
            self._emit(f"{var_name}.def(py::init<>());")

        if _is_copyable_class(cls):
            self._gen_copy_protocol(var_name, cls)

        for method in cls.methods:
            self._gen_method(var_name, cls, method)

        for prop in cls.properties:
            self._gen_property(var_name, cls, prop)

    def _gen_constructor(self, var_name: str, cls: ClassInfo, ctor: ConstructorInfo):
        if not ctor.params:
            docstring = _get_docstring_arg(ctor.annotation)
            self._emit(f"{var_name}.def(py::init<>(){docstring});")
        else:
            type_args = ", ".join(p.type_spelling for p in ctor.params)
            py_args = _format_py_args(ctor.params, self._class_names)
            docstring = _get_docstring_arg(ctor.annotation)
            self._emit(
                f"{var_name}.def(py::init<{type_args}>()"
                f"{py_args}{docstring});"
            )

    def _gen_copy_protocol(self, var_name: str, cls: ClassInfo):
        self._emit(
            f'{var_name}.def("__copy__", '
            f"[](const {cls.name} &self) {{ return {cls.name}(self); }});"
        )
        self._emit(
            f'{var_name}.def("__deepcopy__", '
            f"[](const {cls.name} &self, py::dict) {{ return {cls.name}(self); }}, "
            'py::arg("memo"));'
        )

    def _gen_method(self, var_name: str, cls: ClassInfo, method: MethodInfo):
        py_args = _format_py_args(method.params, self._class_names)
        docstring = _get_docstring_arg(method.annotation)
        return_policy = _get_return_policy(method.annotation)

        if method.is_overloaded:
            param_types = ", ".join(p.type_spelling for p in method.params)
            const_suffix = " const" if method.is_const else ""
            cast = (
                f"static_cast<{method.return_type} ({cls.name}::*)"
                f"({param_types}){const_suffix}>"
                f"(&{cls.name}::{method.name})"
            )
            self._emit(
                f'{var_name}.def("{method.name}", {cast}'
                f"{py_args}{return_policy}{docstring});"
            )
        elif method.is_static:
            self._emit(
                f'{var_name}.def_static("{method.name}", '
                f"&{cls.name}::{method.name}"
                f"{py_args}{return_policy}{docstring});"
            )
        else:
            self._emit(
                f'{var_name}.def("{method.name}", '
                f"&{cls.name}::{method.name}"
                f"{py_args}{return_policy}{docstring});"
            )
        self._gen_callable_metadata(var_name, method.name, method.annotation)

    def _gen_property(self, var_name: str, cls: ClassInfo, prop: PropertyInfo):
        docstring = _get_docstring_arg(prop.annotation)
        if prop.is_readonly:
            self._emit(
                f'{var_name}.def_readonly("{prop.name}", '
                f"&{cls.name}::{prop.name}{docstring});"
            )
        else:
            self._emit(
                f'{var_name}.def_readwrite("{prop.name}", '
                f"&{cls.name}::{prop.name}{docstring});"
            )

    def _gen_function(self, func: FunctionInfo):
        py_args = _format_py_args(func.params, self._class_names)
        docstring = _get_docstring_arg(func.annotation)
        return_policy = _get_return_policy(func.annotation)

        if func.is_overloaded:
            param_names = ", ".join(p.name for p in func.params)
            lambda_params = ", ".join(
                f"{p.type_spelling} {p.name}" for p in func.params
            )
            self._emit(
                f'm.def("{func.name}", '
                f"[]({lambda_params}) {{ return {func.name}({param_names}); }}"
                f"{py_args}{return_policy}{docstring});"
            )
        else:
            self._emit(
                f'm.def("{func.name}", &{func.name}'
                f"{py_args}{return_policy}{docstring});"
            )
        self._gen_callable_metadata("m", func.name, func.annotation)

    def _gen_metadata(self, target_expr: str, annotation: Optional[BindAnnotation]):
        if not annotation or not annotation.metadata:
            return

        self._metadata_counter += 1
        obj_name = f"metadataObj{self._metadata_counter}"
        self._emit("{")
        self._indent_inc()
        self._emit(f"py::object {obj_name} = {target_expr};")

        for kind, options in annotation.metadata:
            if kind == "RETURNTYPE":
                self._gen_metadata_dict(obj_name, "_returnTypes", options, use_split_values=False)
                self._gen_ref_local(obj_name)
            elif kind == "EXECSPLIT":
                self._gen_metadata_dict(obj_name, "_execSplits", options, use_split_values=True)
                self._gen_ref_local(obj_name)
            elif kind == "LATENT":
                self._gen_metadata_dict(obj_name, "_latents", options, use_split_values=True)
                self._gen_ref_local(obj_name)
            elif kind == "META":
                self._gen_metadata_dict(obj_name, "_meta", options, use_split_values=False)
                self._gen_meta_class_shortcuts(obj_name, options)
            elif kind == "REGISTER_EVENT":
                self._emit(f'{obj_name}.attr("_eventSignature") = py::bool_(true);')
                self._emit("py::dict eventExecSplits;")
                self._emit('eventExecSplits["default"] = py::make_tuple(py::none());')
                self._emit(f'{obj_name}.attr("_execSplits") = eventExecSplits;')
                self._gen_ref_local(obj_name)
            elif kind == "INVALID_VARS":
                self._gen_metadata_tuple(obj_name, "_invalidVars", options)
            elif kind == "RECT_RANGE_VARS":
                self._gen_metadata_dict(obj_name, "_rectRangeVars", options, use_split_values=False)

        self._indent_dec()
        self._emit("}")

    def _gen_metadata_dict(self, obj_name: str, attr_name: str, options: dict, use_split_values: bool):
        self._metadata_counter += 1
        dict_name = f"metadataDict{self._metadata_counter}"
        self._emit(f"py::dict {dict_name};")
        for key, value in options.items():
            literal = _format_split_literal(value) if use_split_values else _format_py_literal(value)
            self._emit(f'{dict_name}["{_escape_docstring(str(key))}"] = {literal};')
        self._emit(f'{obj_name}.attr("{attr_name}") = {dict_name};')

    def _gen_metadata_tuple(self, obj_name: str, attr_name: str, options: dict):
        values = options.get("vars", "")
        if isinstance(values, str):
            names = [name.strip() for name in values.split(",") if name.strip()]
        else:
            names = []
        tuple_items = ", ".join(f'py::str("{_escape_docstring(name)}")' for name in names)
        if tuple_items:
            self._emit(f'{obj_name}.attr("{attr_name}") = py::make_tuple({tuple_items});')
        else:
            self._emit(f'{obj_name}.attr("{attr_name}") = py::tuple();')

    def _gen_meta_class_shortcuts(self, obj_name: str, options: dict):
        invalid_vars = options.get("InvalidVars")
        if isinstance(invalid_vars, str):
            names = [name.strip() for name in invalid_vars.split(",") if name.strip()]
            tuple_items = ", ".join(f'py::str("{_escape_docstring(name)}")' for name in names)
            if tuple_items:
                self._emit(f'{obj_name}.attr("_invalidVars") = py::make_tuple({tuple_items});')

        rect_range_vars = options.get("RectRangeVars")
        if isinstance(rect_range_vars, str):
            self._metadata_counter += 1
            dict_name = f"metadataDict{self._metadata_counter}"
            self._emit(f"py::dict {dict_name};")
            for pair in rect_range_vars.split(","):
                if ":" not in pair:
                    continue
                key, value = pair.split(":", 1)
                key = key.strip()
                value = value.strip()
                if key and value:
                    self._emit(f'{dict_name}["{_escape_docstring(key)}"] = py::str("{_escape_docstring(value)}");')
            self._emit(f'{obj_name}.attr("_rectRangeVars") = {dict_name};')

    def _gen_ref_local(self, obj_name: str):
        self._emit(f'if (!py::hasattr({obj_name}, "_refLocal")) {{')
        self._indent_inc()
        self._emit(f'{obj_name}.attr("_refLocal") = py::dict();')
        self._indent_dec()
        self._emit("}")

    def _gen_callable_metadata(self, owner_expr: str, name: str, annotation: Optional[BindAnnotation]):
        if not annotation or not annotation.metadata:
            return

        self._metadata_counter += 1
        registry_name = f"metadataRegistry{self._metadata_counter}"
        self._metadata_counter += 1
        record_name = f"metadataRecord{self._metadata_counter}"

        self._emit("{")
        self._indent_inc()
        self._emit(f'if (!py::hasattr({owner_expr}, "__nodeFunctionMeta__")) {{')
        self._indent_inc()
        self._emit(f'{owner_expr}.attr("__nodeFunctionMeta__") = py::dict();')
        self._indent_dec()
        self._emit("}")
        self._emit(f'py::dict {registry_name} = {owner_expr}.attr("__nodeFunctionMeta__");')
        self._emit(f"py::dict {record_name};")

        for kind, options in annotation.metadata:
            if kind == "RETURNTYPE":
                self._gen_record_dict(record_name, "_returnTypes", options, use_split_values=False)
                self._gen_record_ref_local(record_name)
            elif kind == "EXECSPLIT":
                self._gen_record_dict(record_name, "_execSplits", options, use_split_values=True)
                self._gen_record_ref_local(record_name)
            elif kind == "LATENT":
                self._gen_record_dict(record_name, "_latents", options, use_split_values=True)
                self._gen_record_ref_local(record_name)
            elif kind == "META":
                self._gen_record_dict(record_name, "_meta", options, use_split_values=False)
                self._gen_record_meta_shortcuts(record_name, options)
            elif kind == "REGISTER_EVENT":
                self._emit(f'{record_name}["_eventSignature"] = py::bool_(true);')
                self._emit("py::dict eventExecSplits;")
                self._emit('eventExecSplits["default"] = py::make_tuple(py::none());')
                self._emit(f'{record_name}["_execSplits"] = eventExecSplits;')
                self._gen_record_ref_local(record_name)
            elif kind == "INVALID_VARS":
                self._gen_record_tuple(record_name, "_invalidVars", options)
            elif kind == "RECT_RANGE_VARS":
                self._gen_record_dict(record_name, "_rectRangeVars", options, use_split_values=False)

        self._emit(f'{registry_name}["{_escape_docstring(name)}"] = {record_name};')
        self._indent_dec()
        self._emit("}")

    def _gen_record_dict(self, record_name: str, attr_name: str, options: dict, use_split_values: bool):
        self._metadata_counter += 1
        dict_name = f"metadataDict{self._metadata_counter}"
        self._emit(f"py::dict {dict_name};")
        for key, value in options.items():
            literal = _format_split_literal(value) if use_split_values else _format_py_literal(value)
            self._emit(f'{dict_name}["{_escape_docstring(str(key))}"] = {literal};')
        self._emit(f'{record_name}["{attr_name}"] = {dict_name};')

    def _gen_record_tuple(self, record_name: str, attr_name: str, options: dict):
        values = options.get("vars", "")
        if isinstance(values, str):
            names = [name.strip() for name in values.split(",") if name.strip()]
        else:
            names = []
        tuple_items = ", ".join(f'py::str("{_escape_docstring(name)}")' for name in names)
        if tuple_items:
            self._emit(f'{record_name}["{attr_name}"] = py::make_tuple({tuple_items});')
        else:
            self._emit(f'{record_name}["{attr_name}"] = py::tuple();')

    def _gen_record_meta_shortcuts(self, record_name: str, options: dict):
        general_data_vars = options.get("GeneralDataVars")
        if isinstance(general_data_vars, str):
            tuple_items = []
            for pair in general_data_vars.split(","):
                if ":" not in pair:
                    continue
                name, data_type = pair.split(":", 1)
                name = name.strip()
                data_type = data_type.strip()
                if name and data_type:
                    tuple_items.append(
                        f'py::make_tuple(py::str("{_escape_docstring(name)}"), '
                        f'py::str("{_escape_docstring(data_type)}"))'
                    )
            value = f'py::make_tuple({", ".join(tuple_items)})' if tuple_items else "py::tuple()"
            self._metadata_counter += 1
            meta_name = f"metadataDict{self._metadata_counter}"
            self._emit(f'py::dict {meta_name} = py::cast<py::dict>({record_name}["_meta"]);')
            self._emit(f'{meta_name}["GeneralDataVars"] = {value};')

        invalid_vars = options.get("InvalidVars")
        if isinstance(invalid_vars, str):
            names = [name.strip() for name in invalid_vars.split(",") if name.strip()]
            tuple_items = ", ".join(f'py::str("{_escape_docstring(name)}")' for name in names)
            if tuple_items:
                self._emit(f'{record_name}["_invalidVars"] = py::make_tuple({tuple_items});')

        rect_range_vars = options.get("RectRangeVars")
        if isinstance(rect_range_vars, str):
            self._metadata_counter += 1
            dict_name = f"metadataDict{self._metadata_counter}"
            self._emit(f"py::dict {dict_name};")
            for pair in rect_range_vars.split(","):
                if ":" not in pair:
                    continue
                key, value = pair.split(":", 1)
                key = key.strip()
                value = value.strip()
                if key and value:
                    self._emit(f'{dict_name}["{_escape_docstring(key)}"] = py::str("{_escape_docstring(value)}");')
            self._emit(f'{record_name}["_rectRangeVars"] = {dict_name};')

    def _gen_record_ref_local(self, record_name: str):
        self._emit(f'{record_name}["_refLocal"] = py::dict();')


class CMakeGen:
    def __init__(self, project_name: str):
        self.project_name = project_name

    def generate(
        self,
        source_files: list[str],
        generated_binding: str,
        needs_sfml: bool = False,
        extra_include_dirs: list[str] = None,
    ) -> str:
        lines = [
            "# ============================================================================",
            f"# AUTO-GENERATED by Ludork Bindgen - DO NOT EDIT",
            f"# Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "# ============================================================================",
            "",
            f"project({self.project_name})",
            "",
        ]

        all_sources = [f'"{generated_binding}"'] + [f'"{s}"' for s in source_files]
        lines.append(f"pybind11_add_module({self.project_name}")
        for src in all_sources:
            lines.append(f"    {src}")
        lines.append(")")
        lines.append("")

        lines.append(f"ConfigureTarget({self.project_name})")

        if needs_sfml:
            lines.append(f"ConfigureSFMLTarget({self.project_name})")

        if extra_include_dirs:
            lines.append("")
            for inc_dir in extra_include_dirs:
                cmake_inc_dir = inc_dir.replace("\\", "/")
                lines.append(f"target_include_directories({self.project_name} PRIVATE")
                lines.append(f'    "{cmake_inc_dir}"')
                lines.append(")")

        lines.append("")
        return "\n".join(lines)
