-- AUTO-GENERATED by Ludork General Data. DO NOT EDIT.
local AttributeSet = require("Global.Gameplay.AttributeSet")

local ClassAttributeSet = {}
ClassAttributeSet.ATTRIBUTE_NAMES = { "name", "desc", "slot" }
ClassAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    slot = { type = "dict", default = {} }
}
ClassAttributeSet = class(ClassAttributeSet, AttributeSet)

local EnemyAttributeSet = {}
EnemyAttributeSet.ATTRIBUTE_NAMES = {
    "name", "desc", "MAXHP", "ATK", "DEF", "EXP", "GOLD", "drops", "special", "ANIMATION_KEY"
}
EnemyAttributeSet.SCHEMA = {
    name = { type = "string", default = "NEW ENEMY" },
    desc = { type = "string", default = "NEW ENEMY DESC" },
    MAXHP = { type = "int", default = 0 },
    ATK = { type = "int", default = 0 },
    DEF = { type = "int", default = 0 },
    EXP = { type = "int", default = 0 },
    GOLD = { type = "int", default = 0 },
    drops = { type = "dict", default = {} },
    special = { type = "dict", default = {} },
    ANIMATION_KEY = { type = "string", default = "" }
}
EnemyAttributeSet = class(EnemyAttributeSet, AttributeSet)

local EquipAttributeSet = {}
EquipAttributeSet.ATTRIBUTE_NAMES = { "name", "desc", "icon", "slot", "attrPlus" }
EquipAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    icon = { type = "file", default = "Icons" },
    slot = { type = "string", default = "" },
    attrPlus = { type = "dict", default = {} }
}
EquipAttributeSet = class(EquipAttributeSet, AttributeSet)

local ItemAttributeSet = {}
ItemAttributeSet.ATTRIBUTE_NAMES = { "name", "desc", "usable", "price", "icon", "cost" }
ItemAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    usable = { type = "bool", default = false },
    price = { type = "int", default = 0 },
    icon = { type = "file", default = "Icons" },
    cost = { type = "bool", default = true }
}
ItemAttributeSet = class(ItemAttributeSet, AttributeSet)

local PlayerAttributeSet = {}
PlayerAttributeSet.ATTRIBUTE_NAMES = {
    "name", "desc", "CLASS", "MAXHP", "HP", "ATK", "DEF", "EXP", "GOLD", "LEVEL", "ANIMATION_KEY"
}
PlayerAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    CLASS = { type = "string", default = "" },
    MAXHP = { type = "int", default = 1000 },
    HP = { type = "int", default = 1000 },
    ATK = { type = "int", default = 10 },
    DEF = { type = "int", default = 10 },
    EXP = { type = "int", default = 0 },
    GOLD = { type = "int", default = 0 },
    LEVEL = { type = "int", default = 1 },
    ANIMATION_KEY = { type = "string", default = "" }
}
PlayerAttributeSet = class(PlayerAttributeSet, AttributeSet)

local SpecialAttributeSet = {}
SpecialAttributeSet.ATTRIBUTE_NAMES = { "name", "desc", "icon" }
SpecialAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    icon = { type = "file", default = "Icons" }
}
SpecialAttributeSet = class(SpecialAttributeSet, AttributeSet)

local StateAttributeSet = {}
StateAttributeSet.ATTRIBUTE_NAMES = { "name", "desc", "icon", "stackable" }
StateAttributeSet.SCHEMA = {
    name = { type = "string", default = "" },
    desc = { type = "string", default = "" },
    icon = { type = "file", default = "Icons" },
    stackable = { type = "bool", default = false }
}
StateAttributeSet = class(StateAttributeSet, AttributeSet)

local Types = {
    ["Class"] = ClassAttributeSet,
    ["Enemy"] = EnemyAttributeSet,
    ["Equip"] = EquipAttributeSet,
    ["Item"] = ItemAttributeSet,
    ["Player"] = PlayerAttributeSet,
    ["Special"] = SpecialAttributeSet,
    ["State"] = StateAttributeSet
}

local GeneralDataTypes = {
    Types = Types,
    ClassAttributeSet = ClassAttributeSet,
    EnemyAttributeSet = EnemyAttributeSet,
    EquipAttributeSet = EquipAttributeSet,
    ItemAttributeSet = ItemAttributeSet,
    PlayerAttributeSet = PlayerAttributeSet,
    SpecialAttributeSet = SpecialAttributeSet,
    StateAttributeSet = StateAttributeSet
}

function GeneralDataTypes.Create(typeName, memberId, memberData)
    assert(rawget(Types, typeName) ~= nil, "General Data type not found: " .. tostring(typeName))
    local attributeType = Types[typeName]
    assert(type(memberId) == "string", "General Data member ID must be a string")
    assert(type(memberData) == "table", "General Data member must be a table")
    ---@type table<string, any>
    local values = { ID = deepcopy(memberId) }
    for _, name in ipairs(attributeType.ATTRIBUTE_NAMES) do
        local value = rawget(memberData, name)
        if value == nil then
            value = attributeType.SCHEMA[name].default
        end
        values[name] = deepcopy(value)
    end
    return attributeType.new(values)
end

return GeneralDataTypes
